#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Herrera\Version\Dumper;
use Herrera\Version\Parser;

$jsonPretty = new Camspiers\JsonPretty\JsonPretty;

$composerMetadata = json_decode(file_get_contents('composer.json'));
$composerMetadata->version = isset($composerMetadata->version) ? $composerMetadata->version : '0.0.0';
$builder = Parser::toBuilder($composerMetadata->version);

switch(isset($argv[1]) ? $argv[1] : 'patch') {
	case 'patch': $builder->incrementPatch(); break;
	case 'minor': $builder->incrementMinor(); break;
	case 'major': $builder->incrementMajor(); break;
	default: echo 'unknown version strategy (patch|minor|major)'; exit();
}

$composerMetadata->version = Dumper::toString($builder);

file_put_contents('composer.json', $jsonPretty->prettify($composerMetadata));

echo 'Update and commit version in composer.json' . PHP_EOL;
system('git add composer.json');
system('git commit -m "Updated version in composer.json"');
echo PHP_EOL;

echo 'tag current state with provided version number' . PHP_EOL;
system('git tag "' . $composerMetadata->version . '"');
echo PHP_EOL;


echo 'push tags to github' . PHP_EOL;
system('git push origin master');
system('git push origin --tags');
echo PHP_EOL;


echo 'create new phar' . PHP_EOL;
system('box build');
system('rm Repository/beard-current.phar');
system('cp Repository/beard-' . $composerMetadata->version . '.phar Repository/beard-current.phar');
echo PHP_EOL;


echo 'update manifest' . PHP_EOL;
$files = scandir('Repository');

$manifest = array();

foreach ($files as $file) {
	if (substr($file, 0, 6) === 'beard-') {
		$sha1 = sha1_file('Repository/' . $file);
		preg_match('/beard-([0-9\.]*).phar/', $file, $match);
		if (isset($match[1])) {
			$manifest[] = array(
				'name' => 'beard.phar',
				'sha1' => $sha1,
				'url' => 'https://raw.github.com/mneuhaus/Beard-Versions/master/' . $file,
				'version' => $match[1]
			);
		}
	}
}

file_put_contents('Repository/manifest.json', $jsonPretty->prettify($manifest));

echo PHP_EOL;


echo 'commit and push repository' . PHP_EOL;
chdir('Repository');
system('git add .');
system('git commit -a -m "Added Version: ' . $composerMetadata->version . '"');
system('git push origin master');
?>