<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: ""
 *
 * Auto generated by famelo/soup 2015-10-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
	'title' => '',
	'description' => '',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' =>
	array (
		'depends' =>
		array (
		),
		'conflicts' =>
		array (
		),
		'suggests' =>
		array (
		),
	),
);