<?php
return array (
  'Exception' => 
  array (
    0 => 'ErrorException',
    1 => 'DOMException',
    2 => 'LogicException',
    3 => 'BadFunctionCallException',
    4 => 'BadMethodCallException',
    5 => 'DomainException',
    6 => 'InvalidArgumentException',
    7 => 'LengthException',
    8 => 'OutOfRangeException',
    9 => 'RuntimeException',
    10 => 'OutOfBoundsException',
    11 => 'OverflowException',
    12 => 'RangeException',
    13 => 'UnderflowException',
    14 => 'UnexpectedValueException',
    15 => 'IntlException',
    16 => 'mysqli_sql_exception',
    17 => 'PDOException',
    18 => 'PharException',
    19 => 'ReflectionException',
    20 => 'SoapFault',
    21 => 'ImagickException',
    22 => 'ImagickDrawException',
    23 => 'ImagickPixelIteratorException',
    24 => 'ImagickPixelException',
    25 => 'TYPO3Fluid\\Fluid\\Exception',
    26 => 'TYPO3Fluid\\Fluid\\Core\\Exception',
    27 => 'TYPO3Fluid\\Fluid\\Core\\Compiler\\StopCompilingException',
    28 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\Exception',
    29 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\UnknownNamespaceException',
    30 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception',
    31 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception\\InvalidVariableException',
    32 => 'TYPO3Fluid\\Fluid\\View\\Exception',
    33 => 'TYPO3Fluid\\Fluid\\View\\Exception\\InvalidSectionException',
    34 => 'TYPO3Fluid\\Fluid\\View\\Exception\\InvalidTemplateResourceException',
    35 => 'Symfony\\Component\\Yaml\\Exception\\RuntimeException',
    36 => 'Symfony\\Component\\Yaml\\Exception\\DumpException',
    37 => 'Symfony\\Component\\Yaml\\Exception\\ParseException',
    38 => 'Symfony\\Component\\Process\\Exception\\InvalidArgumentException',
    39 => 'Symfony\\Component\\Process\\Exception\\LogicException',
    40 => 'Symfony\\Component\\Process\\Exception\\RuntimeException',
    41 => 'Symfony\\Component\\Process\\Exception\\ProcessFailedException',
    42 => 'Symfony\\Component\\Process\\Exception\\ProcessTimedOutException',
    43 => 'Symfony\\Component\\Finder\\Exception\\AccessDeniedException',
    44 => 'Symfony\\Component\\Finder\\Exception\\AdapterFailureException',
    45 => 'Symfony\\Component\\Finder\\Exception\\OperationNotPermitedException',
    46 => 'Symfony\\Component\\Finder\\Exception\\ShellCommandFailureException',
    47 => 'Symfony\\Component\\Filesystem\\Exception\\IOException',
    48 => 'Symfony\\Component\\Filesystem\\Exception\\FileNotFoundException',
    49 => 'Symfony\\Component\\Console\\Exception\\CommandNotFoundException',
    50 => 'Symfony\\Component\\Console\\Exception\\InvalidArgumentException',
    51 => 'Symfony\\Component\\Console\\Exception\\InvalidOptionException',
    52 => 'Symfony\\Component\\Console\\Exception\\LogicException',
    53 => 'Symfony\\Component\\Console\\Exception\\RuntimeException',
    54 => 'Seld\\JsonLint\\ParsingException',
    55 => 'Seld\\JsonLint\\DuplicateKeyException',
    56 => 'PhpParser\\Error',
    57 => 'League\\Flysystem\\Exception',
    58 => 'League\\Flysystem\\FileExistsException',
    59 => 'League\\Flysystem\\FileNotFoundException',
    60 => 'League\\Flysystem\\NotSupportedException',
    61 => 'League\\Flysystem\\Plugin\\PluginNotFoundException',
    62 => 'League\\Flysystem\\RootViolationException',
    63 => 'League\\Flysystem\\UnreadableFileException',
    64 => 'JsonSchema\\Exception\\InvalidArgumentException',
    65 => 'JsonSchema\\Exception\\InvalidSchemaMediaTypeException',
    66 => 'JsonSchema\\Exception\\InvalidSourceUriException',
    67 => 'JsonSchema\\Exception\\JsonDecodingException',
    68 => 'JsonSchema\\Exception\\ResourceNotFoundException',
    69 => 'JsonSchema\\Exception\\UriResolverException',
    70 => 'FastRoute\\BadRouteException',
    71 => 'Dotenv\\Exception\\InvalidCallbackException',
    72 => 'Dotenv\\Exception\\InvalidFileException',
    73 => 'Dotenv\\Exception\\InvalidPathException',
    74 => 'Dotenv\\Exception\\ValidationException',
    75 => 'Doctrine\\Instantiator\\Exception\\InvalidArgumentException',
    76 => 'Doctrine\\Instantiator\\Exception\\UnexpectedValueException',
    77 => 'DeepCopy\\Exception\\CloneException',
  ),
  'Iterator' => 
  array (
    0 => 'Generator',
    1 => 'RecursiveIteratorIterator',
    2 => 'IteratorIterator',
    3 => 'FilterIterator',
    4 => 'RecursiveFilterIterator',
    5 => 'CallbackFilterIterator',
    6 => 'RecursiveCallbackFilterIterator',
    7 => 'ParentIterator',
    8 => 'LimitIterator',
    9 => 'CachingIterator',
    10 => 'RecursiveCachingIterator',
    11 => 'NoRewindIterator',
    12 => 'AppendIterator',
    13 => 'InfiniteIterator',
    14 => 'RegexIterator',
    15 => 'RecursiveRegexIterator',
    16 => 'EmptyIterator',
    17 => 'RecursiveTreeIterator',
    18 => 'ArrayIterator',
    19 => 'RecursiveArrayIterator',
    20 => 'DirectoryIterator',
    21 => 'FilesystemIterator',
    22 => 'RecursiveDirectoryIterator',
    23 => 'GlobIterator',
    24 => 'SplFileObject',
    25 => 'SplTempFileObject',
    26 => 'SplDoublyLinkedList',
    27 => 'SplQueue',
    28 => 'SplStack',
    29 => 'SplHeap',
    30 => 'SplMinHeap',
    31 => 'SplMaxHeap',
    32 => 'SplPriorityQueue',
    33 => 'SplFixedArray',
    34 => 'SplObjectStorage',
    35 => 'MultipleIterator',
    36 => 'IntlIterator',
    37 => 'IntlPartsIterator',
    38 => 'Phar',
    39 => 'PharData',
    40 => 'SimpleXMLIterator',
    41 => 'Imagick',
    42 => 'ImagickPixelIterator',
    43 => 'Symfony\\Component\\Finder\\Iterator\\FilterIterator',
    44 => 'Symfony\\Component\\Finder\\Iterator\\CustomFilterIterator',
    45 => 'Symfony\\Component\\Finder\\Iterator\\DateRangeFilterIterator',
    46 => 'Symfony\\Component\\Finder\\Iterator\\DepthRangeFilterIterator',
    47 => 'Symfony\\Component\\Finder\\Iterator\\ExcludeDirectoryFilterIterator',
    48 => 'Symfony\\Component\\Finder\\Iterator\\MultiplePcreFilterIterator',
    49 => 'Symfony\\Component\\Finder\\Iterator\\FilecontentFilterIterator',
    50 => 'Symfony\\Component\\Finder\\Iterator\\FilenameFilterIterator',
    51 => 'Symfony\\Component\\Finder\\Iterator\\FilePathsIterator',
    52 => 'Symfony\\Component\\Finder\\Iterator\\FileTypeFilterIterator',
    53 => 'Symfony\\Component\\Finder\\Iterator\\PathFilterIterator',
    54 => 'Symfony\\Component\\Finder\\Iterator\\RecursiveDirectoryIterator',
    55 => 'Symfony\\Component\\Finder\\Iterator\\SizeRangeFilterIterator',
  ),
  'Traversable' => 
  array (
    0 => 'Generator',
    1 => 'DatePeriod',
    2 => 'DOMNodeList',
    3 => 'DOMNamedNodeMap',
    4 => 'RecursiveIteratorIterator',
    5 => 'IteratorIterator',
    6 => 'FilterIterator',
    7 => 'RecursiveFilterIterator',
    8 => 'CallbackFilterIterator',
    9 => 'RecursiveCallbackFilterIterator',
    10 => 'ParentIterator',
    11 => 'LimitIterator',
    12 => 'CachingIterator',
    13 => 'RecursiveCachingIterator',
    14 => 'NoRewindIterator',
    15 => 'AppendIterator',
    16 => 'InfiniteIterator',
    17 => 'RegexIterator',
    18 => 'RecursiveRegexIterator',
    19 => 'EmptyIterator',
    20 => 'RecursiveTreeIterator',
    21 => 'ArrayObject',
    22 => 'ArrayIterator',
    23 => 'RecursiveArrayIterator',
    24 => 'DirectoryIterator',
    25 => 'FilesystemIterator',
    26 => 'RecursiveDirectoryIterator',
    27 => 'GlobIterator',
    28 => 'SplFileObject',
    29 => 'SplTempFileObject',
    30 => 'SplDoublyLinkedList',
    31 => 'SplQueue',
    32 => 'SplStack',
    33 => 'SplHeap',
    34 => 'SplMinHeap',
    35 => 'SplMaxHeap',
    36 => 'SplPriorityQueue',
    37 => 'SplFixedArray',
    38 => 'SplObjectStorage',
    39 => 'MultipleIterator',
    40 => 'ResourceBundle',
    41 => 'IntlIterator',
    42 => 'IntlBreakIterator',
    43 => 'IntlRuleBasedBreakIterator',
    44 => 'IntlCodePointBreakIterator',
    45 => 'IntlPartsIterator',
    46 => 'mysqli_result',
    47 => 'PDOStatement',
    48 => 'Phar',
    49 => 'PharData',
    50 => 'SimpleXMLElement',
    51 => 'SimpleXMLIterator',
    52 => 'Imagick',
    53 => 'ImagickPixelIterator',
    54 => 'Symfony\\Component\\Console\\Helper\\HelperSet',
    55 => 'Symfony\\Component\\Finder\\Finder',
    56 => 'Symfony\\Component\\Finder\\Iterator\\FilterIterator',
    57 => 'Symfony\\Component\\Finder\\Iterator\\CustomFilterIterator',
    58 => 'Symfony\\Component\\Finder\\Iterator\\DateRangeFilterIterator',
    59 => 'Symfony\\Component\\Finder\\Iterator\\DepthRangeFilterIterator',
    60 => 'Symfony\\Component\\Finder\\Iterator\\ExcludeDirectoryFilterIterator',
    61 => 'Symfony\\Component\\Finder\\Iterator\\MultiplePcreFilterIterator',
    62 => 'Symfony\\Component\\Finder\\Iterator\\FilecontentFilterIterator',
    63 => 'Symfony\\Component\\Finder\\Iterator\\FilenameFilterIterator',
    64 => 'Symfony\\Component\\Finder\\Iterator\\FilePathsIterator',
    65 => 'Symfony\\Component\\Finder\\Iterator\\FileTypeFilterIterator',
    66 => 'Symfony\\Component\\Finder\\Iterator\\PathFilterIterator',
    67 => 'Symfony\\Component\\Finder\\Iterator\\RecursiveDirectoryIterator',
    68 => 'Symfony\\Component\\Finder\\Iterator\\SizeRangeFilterIterator',
    69 => 'Symfony\\Component\\Finder\\Iterator\\SortableIterator',
  ),
  'DateTimeInterface' => 
  array (
    0 => 'DateTime',
    1 => 'DateTimeImmutable',
  ),
  'DOMNode' => 
  array (
    0 => 'DOMDocumentFragment',
    1 => 'DOMDocument',
    2 => 'DOMCharacterData',
    3 => 'DOMAttr',
    4 => 'DOMElement',
    5 => 'DOMText',
    6 => 'DOMComment',
    7 => 'DOMCdataSection',
    8 => 'DOMDocumentType',
    9 => 'DOMNotation',
    10 => 'DOMEntity',
    11 => 'DOMEntityReference',
    12 => 'DOMProcessingInstruction',
  ),
  'DOMCharacterData' => 
  array (
    0 => 'DOMText',
    1 => 'DOMComment',
    2 => 'DOMCdataSection',
  ),
  'DOMText' => 
  array (
    0 => 'DOMCdataSection',
  ),
  'LogicException' => 
  array (
    0 => 'BadFunctionCallException',
    1 => 'BadMethodCallException',
    2 => 'DomainException',
    3 => 'InvalidArgumentException',
    4 => 'LengthException',
    5 => 'OutOfRangeException',
    6 => 'Symfony\\Component\\Process\\Exception\\InvalidArgumentException',
    7 => 'Symfony\\Component\\Process\\Exception\\LogicException',
    8 => 'Symfony\\Component\\Console\\Exception\\CommandNotFoundException',
    9 => 'Symfony\\Component\\Console\\Exception\\InvalidArgumentException',
    10 => 'Symfony\\Component\\Console\\Exception\\InvalidOptionException',
    11 => 'Symfony\\Component\\Console\\Exception\\LogicException',
    12 => 'League\\Flysystem\\Plugin\\PluginNotFoundException',
    13 => 'League\\Flysystem\\RootViolationException',
    14 => 'JsonSchema\\Exception\\InvalidArgumentException',
    15 => 'JsonSchema\\Exception\\InvalidSourceUriException',
    16 => 'FastRoute\\BadRouteException',
    17 => 'Dotenv\\Exception\\InvalidCallbackException',
    18 => 'Dotenv\\Exception\\InvalidFileException',
    19 => 'Dotenv\\Exception\\InvalidPathException',
    20 => 'Doctrine\\Instantiator\\Exception\\InvalidArgumentException',
  ),
  'BadFunctionCallException' => 
  array (
    0 => 'BadMethodCallException',
  ),
  'RuntimeException' => 
  array (
    0 => 'OutOfBoundsException',
    1 => 'OverflowException',
    2 => 'RangeException',
    3 => 'UnderflowException',
    4 => 'UnexpectedValueException',
    5 => 'mysqli_sql_exception',
    6 => 'PDOException',
    7 => 'TYPO3Fluid\\Fluid\\Exception',
    8 => 'TYPO3Fluid\\Fluid\\Core\\Exception',
    9 => 'TYPO3Fluid\\Fluid\\Core\\Compiler\\StopCompilingException',
    10 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\Exception',
    11 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\UnknownNamespaceException',
    12 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception',
    13 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception\\InvalidVariableException',
    14 => 'TYPO3Fluid\\Fluid\\View\\Exception',
    15 => 'TYPO3Fluid\\Fluid\\View\\Exception\\InvalidSectionException',
    16 => 'TYPO3Fluid\\Fluid\\View\\Exception\\InvalidTemplateResourceException',
    17 => 'Symfony\\Component\\Yaml\\Exception\\RuntimeException',
    18 => 'Symfony\\Component\\Yaml\\Exception\\DumpException',
    19 => 'Symfony\\Component\\Yaml\\Exception\\ParseException',
    20 => 'Symfony\\Component\\Process\\Exception\\RuntimeException',
    21 => 'Symfony\\Component\\Process\\Exception\\ProcessFailedException',
    22 => 'Symfony\\Component\\Process\\Exception\\ProcessTimedOutException',
    23 => 'Symfony\\Component\\Finder\\Exception\\AccessDeniedException',
    24 => 'Symfony\\Component\\Finder\\Exception\\AdapterFailureException',
    25 => 'Symfony\\Component\\Finder\\Exception\\OperationNotPermitedException',
    26 => 'Symfony\\Component\\Finder\\Exception\\ShellCommandFailureException',
    27 => 'Symfony\\Component\\Filesystem\\Exception\\IOException',
    28 => 'Symfony\\Component\\Filesystem\\Exception\\FileNotFoundException',
    29 => 'Symfony\\Component\\Console\\Exception\\RuntimeException',
    30 => 'PhpParser\\Error',
    31 => 'League\\Flysystem\\NotSupportedException',
    32 => 'JsonSchema\\Exception\\InvalidSchemaMediaTypeException',
    33 => 'JsonSchema\\Exception\\JsonDecodingException',
    34 => 'JsonSchema\\Exception\\ResourceNotFoundException',
    35 => 'JsonSchema\\Exception\\UriResolverException',
    36 => 'Dotenv\\Exception\\ValidationException',
    37 => 'Doctrine\\Instantiator\\Exception\\UnexpectedValueException',
    38 => 'DeepCopy\\Exception\\CloneException',
  ),
  'OuterIterator' => 
  array (
    0 => 'RecursiveIteratorIterator',
    1 => 'IteratorIterator',
    2 => 'FilterIterator',
    3 => 'RecursiveFilterIterator',
    4 => 'CallbackFilterIterator',
    5 => 'RecursiveCallbackFilterIterator',
    6 => 'ParentIterator',
    7 => 'LimitIterator',
    8 => 'CachingIterator',
    9 => 'RecursiveCachingIterator',
    10 => 'NoRewindIterator',
    11 => 'AppendIterator',
    12 => 'InfiniteIterator',
    13 => 'RegexIterator',
    14 => 'RecursiveRegexIterator',
    15 => 'RecursiveTreeIterator',
    16 => 'Symfony\\Component\\Finder\\Iterator\\FilterIterator',
    17 => 'Symfony\\Component\\Finder\\Iterator\\CustomFilterIterator',
    18 => 'Symfony\\Component\\Finder\\Iterator\\DateRangeFilterIterator',
    19 => 'Symfony\\Component\\Finder\\Iterator\\DepthRangeFilterIterator',
    20 => 'Symfony\\Component\\Finder\\Iterator\\ExcludeDirectoryFilterIterator',
    21 => 'Symfony\\Component\\Finder\\Iterator\\MultiplePcreFilterIterator',
    22 => 'Symfony\\Component\\Finder\\Iterator\\FilecontentFilterIterator',
    23 => 'Symfony\\Component\\Finder\\Iterator\\FilenameFilterIterator',
    24 => 'Symfony\\Component\\Finder\\Iterator\\FileTypeFilterIterator',
    25 => 'Symfony\\Component\\Finder\\Iterator\\PathFilterIterator',
    26 => 'Symfony\\Component\\Finder\\Iterator\\SizeRangeFilterIterator',
  ),
  'IteratorIterator' => 
  array (
    0 => 'FilterIterator',
    1 => 'RecursiveFilterIterator',
    2 => 'CallbackFilterIterator',
    3 => 'RecursiveCallbackFilterIterator',
    4 => 'ParentIterator',
    5 => 'LimitIterator',
    6 => 'CachingIterator',
    7 => 'RecursiveCachingIterator',
    8 => 'NoRewindIterator',
    9 => 'AppendIterator',
    10 => 'InfiniteIterator',
    11 => 'RegexIterator',
    12 => 'RecursiveRegexIterator',
    13 => 'Symfony\\Component\\Finder\\Iterator\\FilterIterator',
    14 => 'Symfony\\Component\\Finder\\Iterator\\CustomFilterIterator',
    15 => 'Symfony\\Component\\Finder\\Iterator\\DateRangeFilterIterator',
    16 => 'Symfony\\Component\\Finder\\Iterator\\DepthRangeFilterIterator',
    17 => 'Symfony\\Component\\Finder\\Iterator\\ExcludeDirectoryFilterIterator',
    18 => 'Symfony\\Component\\Finder\\Iterator\\MultiplePcreFilterIterator',
    19 => 'Symfony\\Component\\Finder\\Iterator\\FilecontentFilterIterator',
    20 => 'Symfony\\Component\\Finder\\Iterator\\FilenameFilterIterator',
    21 => 'Symfony\\Component\\Finder\\Iterator\\FileTypeFilterIterator',
    22 => 'Symfony\\Component\\Finder\\Iterator\\PathFilterIterator',
    23 => 'Symfony\\Component\\Finder\\Iterator\\SizeRangeFilterIterator',
  ),
  'RecursiveIterator' => 
  array (
    0 => 'RecursiveFilterIterator',
    1 => 'RecursiveCallbackFilterIterator',
    2 => 'ParentIterator',
    3 => 'RecursiveCachingIterator',
    4 => 'RecursiveRegexIterator',
    5 => 'RecursiveArrayIterator',
    6 => 'RecursiveDirectoryIterator',
    7 => 'SplFileObject',
    8 => 'SplTempFileObject',
    9 => 'Phar',
    10 => 'PharData',
    11 => 'SimpleXMLIterator',
    12 => 'Symfony\\Component\\Finder\\Iterator\\ExcludeDirectoryFilterIterator',
    13 => 'Symfony\\Component\\Finder\\Iterator\\RecursiveDirectoryIterator',
  ),
  'FilterIterator' => 
  array (
    0 => 'RecursiveFilterIterator',
    1 => 'CallbackFilterIterator',
    2 => 'RecursiveCallbackFilterIterator',
    3 => 'ParentIterator',
    4 => 'RegexIterator',
    5 => 'RecursiveRegexIterator',
    6 => 'Symfony\\Component\\Finder\\Iterator\\FilterIterator',
    7 => 'Symfony\\Component\\Finder\\Iterator\\CustomFilterIterator',
    8 => 'Symfony\\Component\\Finder\\Iterator\\DateRangeFilterIterator',
    9 => 'Symfony\\Component\\Finder\\Iterator\\DepthRangeFilterIterator',
    10 => 'Symfony\\Component\\Finder\\Iterator\\ExcludeDirectoryFilterIterator',
    11 => 'Symfony\\Component\\Finder\\Iterator\\MultiplePcreFilterIterator',
    12 => 'Symfony\\Component\\Finder\\Iterator\\FilecontentFilterIterator',
    13 => 'Symfony\\Component\\Finder\\Iterator\\FilenameFilterIterator',
    14 => 'Symfony\\Component\\Finder\\Iterator\\FileTypeFilterIterator',
    15 => 'Symfony\\Component\\Finder\\Iterator\\PathFilterIterator',
    16 => 'Symfony\\Component\\Finder\\Iterator\\SizeRangeFilterIterator',
  ),
  'CallbackFilterIterator' => 
  array (
    0 => 'RecursiveCallbackFilterIterator',
  ),
  'RecursiveFilterIterator' => 
  array (
    0 => 'ParentIterator',
  ),
  'ArrayAccess' => 
  array (
    0 => 'CachingIterator',
    1 => 'RecursiveCachingIterator',
    2 => 'ArrayObject',
    3 => 'ArrayIterator',
    4 => 'RecursiveArrayIterator',
    5 => 'SplDoublyLinkedList',
    6 => 'SplQueue',
    7 => 'SplStack',
    8 => 'SplFixedArray',
    9 => 'SplObjectStorage',
    10 => 'Phar',
    11 => 'PharData',
    12 => 'TYPO3Fluid\\Fluid\\Core\\Variables\\StandardVariableProvider',
    13 => 'TYPO3Fluid\\Fluid\\Core\\Variables\\ChainedVariableProvider',
    14 => 'TYPO3Fluid\\Fluid\\Core\\Variables\\JSONVariableProvider',
    15 => 'Symfony\\Component\\Finder\\Iterator\\FilePathsIterator',
  ),
  'Countable' => 
  array (
    0 => 'CachingIterator',
    1 => 'RecursiveCachingIterator',
    2 => 'ArrayObject',
    3 => 'ArrayIterator',
    4 => 'RecursiveArrayIterator',
    5 => 'GlobIterator',
    6 => 'SplDoublyLinkedList',
    7 => 'SplQueue',
    8 => 'SplStack',
    9 => 'SplHeap',
    10 => 'SplMinHeap',
    11 => 'SplMaxHeap',
    12 => 'SplPriorityQueue',
    13 => 'SplFixedArray',
    14 => 'SplObjectStorage',
    15 => 'Phar',
    16 => 'PharData',
    17 => 'SimpleXMLIterator',
    18 => 'Symfony\\Component\\Finder\\Finder',
    19 => 'Symfony\\Component\\Finder\\Iterator\\FilePathsIterator',
  ),
  'CachingIterator' => 
  array (
    0 => 'RecursiveCachingIterator',
  ),
  'RegexIterator' => 
  array (
    0 => 'RecursiveRegexIterator',
  ),
  'RecursiveIteratorIterator' => 
  array (
    0 => 'RecursiveTreeIterator',
  ),
  'IteratorAggregate' => 
  array (
    0 => 'ArrayObject',
    1 => 'Symfony\\Component\\Console\\Helper\\HelperSet',
    2 => 'Symfony\\Component\\Finder\\Finder',
    3 => 'Symfony\\Component\\Finder\\Iterator\\SortableIterator',
  ),
  'Serializable' => 
  array (
    0 => 'ArrayObject',
    1 => 'ArrayIterator',
    2 => 'RecursiveArrayIterator',
    3 => 'SplDoublyLinkedList',
    4 => 'SplQueue',
    5 => 'SplStack',
    6 => 'SplObjectStorage',
    7 => 'Symfony\\Component\\Finder\\Iterator\\FilePathsIterator',
  ),
  'SeekableIterator' => 
  array (
    0 => 'ArrayIterator',
    1 => 'RecursiveArrayIterator',
    2 => 'DirectoryIterator',
    3 => 'FilesystemIterator',
    4 => 'RecursiveDirectoryIterator',
    5 => 'GlobIterator',
    6 => 'SplFileObject',
    7 => 'SplTempFileObject',
    8 => 'Phar',
    9 => 'PharData',
    10 => 'Symfony\\Component\\Finder\\Iterator\\FilePathsIterator',
    11 => 'Symfony\\Component\\Finder\\Iterator\\RecursiveDirectoryIterator',
  ),
  'ArrayIterator' => 
  array (
    0 => 'RecursiveArrayIterator',
    1 => 'Symfony\\Component\\Finder\\Iterator\\FilePathsIterator',
  ),
  'SplFileInfo' => 
  array (
    0 => 'DirectoryIterator',
    1 => 'FilesystemIterator',
    2 => 'RecursiveDirectoryIterator',
    3 => 'GlobIterator',
    4 => 'SplFileObject',
    5 => 'SplTempFileObject',
    6 => 'Phar',
    7 => 'PharData',
    8 => 'PharFileInfo',
    9 => 'Symfony\\Component\\Finder\\Iterator\\RecursiveDirectoryIterator',
    10 => 'Symfony\\Component\\Finder\\SplFileInfo',
  ),
  'DirectoryIterator' => 
  array (
    0 => 'FilesystemIterator',
    1 => 'RecursiveDirectoryIterator',
    2 => 'GlobIterator',
    3 => 'Phar',
    4 => 'PharData',
    5 => 'Symfony\\Component\\Finder\\Iterator\\RecursiveDirectoryIterator',
  ),
  'FilesystemIterator' => 
  array (
    0 => 'RecursiveDirectoryIterator',
    1 => 'GlobIterator',
    2 => 'Phar',
    3 => 'PharData',
    4 => 'Symfony\\Component\\Finder\\Iterator\\RecursiveDirectoryIterator',
  ),
  'SplFileObject' => 
  array (
    0 => 'SplTempFileObject',
  ),
  'SplDoublyLinkedList' => 
  array (
    0 => 'SplQueue',
    1 => 'SplStack',
  ),
  'SplHeap' => 
  array (
    0 => 'SplMinHeap',
    1 => 'SplMaxHeap',
  ),
  'IntlCalendar' => 
  array (
    0 => 'IntlGregorianCalendar',
  ),
  'IntlBreakIterator' => 
  array (
    0 => 'IntlRuleBasedBreakIterator',
    1 => 'IntlCodePointBreakIterator',
  ),
  'IntlIterator' => 
  array (
    0 => 'IntlPartsIterator',
  ),
  'SessionHandlerInterface' => 
  array (
    0 => 'SessionHandler',
  ),
  'SessionIdInterface' => 
  array (
    0 => 'SessionHandler',
  ),
  'RecursiveDirectoryIterator' => 
  array (
    0 => 'Phar',
    1 => 'PharData',
    2 => 'Symfony\\Component\\Finder\\Iterator\\RecursiveDirectoryIterator',
  ),
  'Reflector' => 
  array (
    0 => 'ReflectionFunctionAbstract',
    1 => 'ReflectionFunction',
    2 => 'ReflectionParameter',
    3 => 'ReflectionMethod',
    4 => 'ReflectionClass',
    5 => 'ReflectionObject',
    6 => 'ReflectionProperty',
    7 => 'ReflectionExtension',
    8 => 'ReflectionZendExtension',
  ),
  'ReflectionFunctionAbstract' => 
  array (
    0 => 'ReflectionFunction',
    1 => 'ReflectionMethod',
  ),
  'ReflectionClass' => 
  array (
    0 => 'ReflectionObject',
  ),
  'SimpleXMLElement' => 
  array (
    0 => 'SimpleXMLIterator',
  ),
  'Symfony\\Component\\Console\\Application' => 
  array (
    0 => 'Famelo\\Beard\\Application',
  ),
  'Symfony\\Component\\Console\\Helper\\HelperInterface' => 
  array (
    0 => 'Symfony\\Component\\Console\\Helper\\Helper',
    1 => 'Symfony\\Component\\Console\\Helper\\FormatterHelper',
    2 => 'Symfony\\Component\\Console\\Helper\\InputAwareHelper',
    3 => 'Symfony\\Component\\Console\\Helper\\DialogHelper',
    4 => 'Symfony\\Component\\Console\\Helper\\ProgressHelper',
    5 => 'Symfony\\Component\\Console\\Helper\\TableHelper',
    6 => 'Symfony\\Component\\Console\\Helper\\DebugFormatterHelper',
    7 => 'Symfony\\Component\\Console\\Helper\\ProcessHelper',
    8 => 'Symfony\\Component\\Console\\Helper\\QuestionHelper',
    9 => 'Famelo\\Beard\\Helper\\ConfigurationHelper',
    10 => 'Symfony\\Component\\Console\\Helper\\DescriptorHelper',
    11 => 'Symfony\\Component\\Console\\Helper\\SymfonyQuestionHelper',
  ),
  'Symfony\\Component\\Console\\Helper\\Helper' => 
  array (
    0 => 'Symfony\\Component\\Console\\Helper\\FormatterHelper',
    1 => 'Symfony\\Component\\Console\\Helper\\InputAwareHelper',
    2 => 'Symfony\\Component\\Console\\Helper\\DialogHelper',
    3 => 'Symfony\\Component\\Console\\Helper\\ProgressHelper',
    4 => 'Symfony\\Component\\Console\\Helper\\TableHelper',
    5 => 'Symfony\\Component\\Console\\Helper\\DebugFormatterHelper',
    6 => 'Symfony\\Component\\Console\\Helper\\ProcessHelper',
    7 => 'Symfony\\Component\\Console\\Helper\\QuestionHelper',
    8 => 'Famelo\\Beard\\Helper\\ConfigurationHelper',
    9 => 'Symfony\\Component\\Console\\Helper\\DescriptorHelper',
    10 => 'Symfony\\Component\\Console\\Helper\\SymfonyQuestionHelper',
  ),
  'Symfony\\Component\\Console\\Input\\InputAwareInterface' => 
  array (
    0 => 'Symfony\\Component\\Console\\Helper\\InputAwareHelper',
    1 => 'Symfony\\Component\\Console\\Helper\\DialogHelper',
  ),
  'Symfony\\Component\\Console\\Helper\\InputAwareHelper' => 
  array (
    0 => 'Symfony\\Component\\Console\\Helper\\DialogHelper',
  ),
  'Symfony\\Component\\Console\\Output\\OutputInterface' => 
  array (
    0 => 'Symfony\\Component\\Console\\Output\\NullOutput',
    1 => 'Symfony\\Component\\Console\\Output\\Output',
    2 => 'Symfony\\Component\\Console\\Output\\StreamOutput',
    3 => 'Symfony\\Component\\Console\\Output\\ConsoleOutput',
    4 => 'Symfony\\Component\\Console\\Output\\BufferedOutput',
    5 => 'Symfony\\Component\\Console\\Style\\OutputStyle',
    6 => 'Symfony\\Component\\Console\\Style\\SymfonyStyle',
  ),
  'JsonSchema\\Constraints\\ConstraintInterface' => 
  array (
    0 => 'JsonSchema\\Constraints\\Constraint',
    1 => 'JsonSchema\\Validator',
    2 => 'JsonSchema\\Constraints\\CollectionConstraint',
    3 => 'JsonSchema\\Constraints\\EnumConstraint',
    4 => 'JsonSchema\\Constraints\\FormatConstraint',
    5 => 'JsonSchema\\Constraints\\NumberConstraint',
    6 => 'JsonSchema\\Constraints\\ObjectConstraint',
    7 => 'JsonSchema\\Constraints\\SchemaConstraint',
    8 => 'JsonSchema\\Constraints\\StringConstraint',
    9 => 'JsonSchema\\Constraints\\TypeConstraint',
    10 => 'JsonSchema\\Constraints\\UndefinedConstraint',
  ),
  'JsonSchema\\Constraints\\Constraint' => 
  array (
    0 => 'JsonSchema\\Validator',
    1 => 'JsonSchema\\Constraints\\CollectionConstraint',
    2 => 'JsonSchema\\Constraints\\EnumConstraint',
    3 => 'JsonSchema\\Constraints\\FormatConstraint',
    4 => 'JsonSchema\\Constraints\\NumberConstraint',
    5 => 'JsonSchema\\Constraints\\ObjectConstraint',
    6 => 'JsonSchema\\Constraints\\SchemaConstraint',
    7 => 'JsonSchema\\Constraints\\StringConstraint',
    8 => 'JsonSchema\\Constraints\\TypeConstraint',
    9 => 'JsonSchema\\Constraints\\UndefinedConstraint',
  ),
  'Symfony\\Component\\Console\\Command\\Command' => 
  array (
    0 => 'Symfony\\Component\\Console\\Command\\HelpCommand',
    1 => 'Symfony\\Component\\Console\\Command\\ListCommand',
    2 => 'Famelo\\Beard\\Command\\AbstractSettingsCommand',
    3 => 'Famelo\\Beard\\Command\\Cache\\Clear',
    4 => 'Famelo\\Beard\\Command\\Cache\\Warmup',
    5 => 'Famelo\\Beard\\Command\\Backup',
    6 => 'Famelo\\Beard\\Command\\Backup\\Userdata',
    7 => 'Famelo\\Beard\\Command\\Backup\\Database',
    8 => 'Famelo\\Beard\\Command\\Database\\Clear',
    9 => 'Famelo\\Beard\\Command\\Database\\Compare',
    10 => 'Famelo\\Beard\\Command\\Database\\Restore',
    11 => 'Famelo\\Beard\\Command\\Database\\Snapshot',
    12 => 'Famelo\\Beard\\Command\\Database\\Truncate',
    13 => 'Famelo\\Beard\\Command\\Site\\Hash',
    14 => 'Famelo\\Beard\\Command\\Patch',
    15 => 'Famelo\\Beard\\Command\\Status',
    16 => 'Famelo\\Beard\\Command\\Reset',
    17 => 'Famelo\\Beard\\Command\\Setup',
    18 => 'Famelo\\Beard\\Command\\Lock',
    19 => 'Famelo\\Beard\\Command\\Scaffold',
    20 => 'Famelo\\Beard\\Command\\Ssh\\Keygen',
    21 => 'Stecman\\Component\\Symfony\\Console\\BashCompletion\\CompletionCommand',
  ),
  'Famelo\\Beard\\Command\\AbstractSettingsCommand' => 
  array (
    0 => 'Famelo\\Beard\\Command\\Cache\\Clear',
    1 => 'Famelo\\Beard\\Command\\Cache\\Warmup',
    2 => 'Famelo\\Beard\\Command\\Backup',
    3 => 'Famelo\\Beard\\Command\\Backup\\Userdata',
    4 => 'Famelo\\Beard\\Command\\Backup\\Database',
    5 => 'Famelo\\Beard\\Command\\Database\\Clear',
    6 => 'Famelo\\Beard\\Command\\Database\\Compare',
    7 => 'Famelo\\Beard\\Command\\Database\\Restore',
    8 => 'Famelo\\Beard\\Command\\Database\\Snapshot',
    9 => 'Famelo\\Beard\\Command\\Database\\Truncate',
  ),
  'Famelo\\Beard\\Command\\Backup\\Database' => 
  array (
    0 => 'Famelo\\Beard\\Command\\Database\\Clear',
    1 => 'Famelo\\Beard\\Command\\Database\\Truncate',
  ),
  'Symfony\\Component\\Console\\Input\\InputInterface' => 
  array (
    0 => 'Symfony\\Component\\Console\\Input\\Input',
    1 => 'Symfony\\Component\\Console\\Input\\ArgvInput',
    2 => 'Symfony\\Component\\Console\\Input\\ArrayInput',
    3 => 'Symfony\\Component\\Console\\Input\\StringInput',
  ),
  'Symfony\\Component\\Console\\Input\\Input' => 
  array (
    0 => 'Symfony\\Component\\Console\\Input\\ArgvInput',
    1 => 'Symfony\\Component\\Console\\Input\\ArrayInput',
    2 => 'Symfony\\Component\\Console\\Input\\StringInput',
  ),
  'Symfony\\Component\\Console\\Output\\Output' => 
  array (
    0 => 'Symfony\\Component\\Console\\Output\\StreamOutput',
    1 => 'Symfony\\Component\\Console\\Output\\ConsoleOutput',
    2 => 'Symfony\\Component\\Console\\Output\\BufferedOutput',
  ),
  'Symfony\\Component\\Console\\Output\\ConsoleOutputInterface' => 
  array (
    0 => 'Symfony\\Component\\Console\\Output\\ConsoleOutput',
  ),
  'Symfony\\Component\\Console\\Output\\StreamOutput' => 
  array (
    0 => 'Symfony\\Component\\Console\\Output\\ConsoleOutput',
  ),
  'Symfony\\Component\\Console\\Formatter\\OutputFormatterInterface' => 
  array (
    0 => 'Symfony\\Component\\Console\\Formatter\\OutputFormatter',
  ),
  'Symfony\\Component\\Console\\Formatter\\OutputFormatterStyleInterface' => 
  array (
    0 => 'Symfony\\Component\\Console\\Formatter\\OutputFormatterStyle',
  ),
  'phpseclib\\Crypt\\Base' => 
  array (
    0 => 'phpseclib\\Crypt\\Rijndael',
    1 => 'phpseclib\\Crypt\\AES',
    2 => 'phpseclib\\Crypt\\Blowfish',
    3 => 'phpseclib\\Crypt\\DES',
    4 => 'phpseclib\\Crypt\\RC2',
    5 => 'phpseclib\\Crypt\\RC4',
    6 => 'phpseclib\\Crypt\\TripleDES',
    7 => 'phpseclib\\Crypt\\Twofish',
  ),
  'phpseclib\\Crypt\\Rijndael' => 
  array (
    0 => 'phpseclib\\Crypt\\AES',
  ),
  'phpseclib\\Crypt\\DES' => 
  array (
    0 => 'phpseclib\\Crypt\\TripleDES',
  ),
  'phpseclib\\Net\\SSH2' => 
  array (
    0 => 'phpseclib\\Net\\SFTP',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Cache\\FluidCacheInterface' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Cache\\SimpleFileCache',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Parser\\ParsedTemplateInterface' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Compiler\\AbstractCompiledTemplate',
    1 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\ParsingState',
  ),
  'TYPO3Fluid\\Fluid\\Exception' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Exception',
    1 => 'TYPO3Fluid\\Fluid\\Core\\Compiler\\StopCompilingException',
    2 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\Exception',
    3 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\UnknownNamespaceException',
    4 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception',
    5 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception\\InvalidVariableException',
    6 => 'TYPO3Fluid\\Fluid\\View\\Exception',
    7 => 'TYPO3Fluid\\Fluid\\View\\Exception\\InvalidSectionException',
    8 => 'TYPO3Fluid\\Fluid\\View\\Exception\\InvalidTemplateResourceException',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Exception' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Compiler\\StopCompilingException',
    1 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\Exception',
    2 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\UnknownNamespaceException',
    3 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception',
    4 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception\\InvalidVariableException',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Parser\\InterceptorInterface' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\Interceptor\\Escape',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\NodeInterface' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode',
    1 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ArrayNode',
    2 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\BooleanNode',
    3 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\EscapingNode',
    4 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\AbstractExpressionNode',
    5 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\CastingExpressionNode',
    6 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\MathExpressionNode',
    7 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\TernaryExpressionNode',
    8 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\NumericNode',
    9 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ObjectAccessorNode',
    10 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\RootNode',
    11 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\TextNode',
    12 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ArrayNode',
    1 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\BooleanNode',
    2 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\EscapingNode',
    3 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\AbstractExpressionNode',
    4 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\CastingExpressionNode',
    5 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\MathExpressionNode',
    6 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\TernaryExpressionNode',
    7 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\NumericNode',
    8 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ObjectAccessorNode',
    9 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\RootNode',
    10 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\TextNode',
    11 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\ExpressionNodeInterface' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\AbstractExpressionNode',
    1 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\CastingExpressionNode',
    2 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\MathExpressionNode',
    3 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\TernaryExpressionNode',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\AbstractExpressionNode' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\CastingExpressionNode',
    1 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\MathExpressionNode',
    2 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\Expression\\TernaryExpressionNode',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Parser\\TemplateProcessorInterface' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\TemplateProcessor\\NamespaceDetectionTemplateProcessor',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Parser\\Exception' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Parser\\UnknownNamespaceException',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Rendering\\RenderingContextInterface' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Rendering\\RenderingContext',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Variables\\VariableProviderInterface' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Variables\\StandardVariableProvider',
    1 => 'TYPO3Fluid\\Fluid\\Core\\Variables\\ChainedVariableProvider',
    2 => 'TYPO3Fluid\\Fluid\\Core\\Variables\\JSONVariableProvider',
  ),
  'TYPO3Fluid\\Fluid\\Core\\Variables\\StandardVariableProvider' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\Variables\\ChainedVariableProvider',
    1 => 'TYPO3Fluid\\Fluid\\Core\\Variables\\JSONVariableProvider',
  ),
  'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInterface' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper',
    1 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper',
    2 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractTagBasedViewHelper',
    3 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\AliasViewHelper',
    4 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\CaseViewHelper',
    5 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\CommentViewHelper',
    6 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\CountViewHelper',
    7 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\CycleViewHelper',
    8 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\DebugViewHelper',
    9 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\DefaultCaseViewHelper',
    10 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\ElseViewHelper',
    11 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\Format\\CdataViewHelper',
    12 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\Format\\HtmlspecialcharsViewHelper',
    13 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\Format\\PrintfViewHelper',
    14 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\Format\\RawViewHelper',
    15 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\ForViewHelper',
    16 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\GroupedForViewHelper',
    17 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\IfViewHelper',
    18 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\LayoutViewHelper',
    19 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\OrViewHelper',
    20 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper',
    21 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\SectionViewHelper',
    22 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\SpacelessViewHelper',
    23 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\SwitchViewHelper',
    24 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\ThenViewHelper',
    25 => 'Famelo\\Beard\\ViewHelpers\\BlockViewHelper',
    26 => 'Famelo\\Beard\\ViewHelpers\\Form\\FieldViewHelper',
    27 => 'Famelo\\Beard\\ViewHelpers\\Form\\NameViewHelper',
    28 => 'Famelo\\Beard\\ViewHelpers\\Format\\ClassIdViewHelper',
    29 => 'Famelo\\Beard\\ViewHelpers\\Format\\ClassPartialViewHelper',
    30 => 'Famelo\\Beard\\ViewHelpers\\String\\CutSuffixViewHelper',
  ),
  'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper',
    1 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractTagBasedViewHelper',
    2 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\AliasViewHelper',
    3 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\CaseViewHelper',
    4 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\CommentViewHelper',
    5 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\CountViewHelper',
    6 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\CycleViewHelper',
    7 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\DebugViewHelper',
    8 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\DefaultCaseViewHelper',
    9 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\ElseViewHelper',
    10 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\Format\\CdataViewHelper',
    11 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\Format\\HtmlspecialcharsViewHelper',
    12 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\Format\\PrintfViewHelper',
    13 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\Format\\RawViewHelper',
    14 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\ForViewHelper',
    15 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\GroupedForViewHelper',
    16 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\IfViewHelper',
    17 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\LayoutViewHelper',
    18 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\OrViewHelper',
    19 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper',
    20 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\SectionViewHelper',
    21 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\SpacelessViewHelper',
    22 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\SwitchViewHelper',
    23 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\ThenViewHelper',
    24 => 'Famelo\\Beard\\ViewHelpers\\BlockViewHelper',
    25 => 'Famelo\\Beard\\ViewHelpers\\Form\\FieldViewHelper',
    26 => 'Famelo\\Beard\\ViewHelpers\\Form\\NameViewHelper',
    27 => 'Famelo\\Beard\\ViewHelpers\\Format\\ClassIdViewHelper',
    28 => 'Famelo\\Beard\\ViewHelpers\\Format\\ClassPartialViewHelper',
    29 => 'Famelo\\Beard\\ViewHelpers\\String\\CutSuffixViewHelper',
  ),
  'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception\\InvalidVariableException',
  ),
  'TYPO3Fluid\\Fluid\\View\\ViewInterface' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\View\\AbstractView',
    1 => 'TYPO3Fluid\\Fluid\\View\\AbstractTemplateView',
    2 => 'TYPO3Fluid\\Fluid\\View\\TemplateView',
  ),
  'TYPO3Fluid\\Fluid\\View\\AbstractView' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\View\\AbstractTemplateView',
    1 => 'TYPO3Fluid\\Fluid\\View\\TemplateView',
  ),
  'TYPO3Fluid\\Fluid\\View\\Exception' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\View\\Exception\\InvalidSectionException',
    1 => 'TYPO3Fluid\\Fluid\\View\\Exception\\InvalidTemplateResourceException',
  ),
  'TYPO3Fluid\\Fluid\\View\\AbstractTemplateView' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\View\\TemplateView',
  ),
  'TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper' => 
  array (
    0 => 'TYPO3Fluid\\Fluid\\ViewHelpers\\IfViewHelper',
  ),
  'Symfony\\Component\\Yaml\\Exception\\ExceptionInterface' => 
  array (
    0 => 'Symfony\\Component\\Yaml\\Exception\\RuntimeException',
    1 => 'Symfony\\Component\\Yaml\\Exception\\DumpException',
    2 => 'Symfony\\Component\\Yaml\\Exception\\ParseException',
  ),
  'Symfony\\Component\\Yaml\\Exception\\RuntimeException' => 
  array (
    0 => 'Symfony\\Component\\Yaml\\Exception\\DumpException',
    1 => 'Symfony\\Component\\Yaml\\Exception\\ParseException',
  ),
  'Symfony\\Component\\Process\\Exception\\ExceptionInterface' => 
  array (
    0 => 'Symfony\\Component\\Process\\Exception\\InvalidArgumentException',
    1 => 'Symfony\\Component\\Process\\Exception\\LogicException',
    2 => 'Symfony\\Component\\Process\\Exception\\RuntimeException',
    3 => 'Symfony\\Component\\Process\\Exception\\ProcessFailedException',
    4 => 'Symfony\\Component\\Process\\Exception\\ProcessTimedOutException',
  ),
  'InvalidArgumentException' => 
  array (
    0 => 'Symfony\\Component\\Process\\Exception\\InvalidArgumentException',
    1 => 'Symfony\\Component\\Console\\Exception\\CommandNotFoundException',
    2 => 'Symfony\\Component\\Console\\Exception\\InvalidArgumentException',
    3 => 'Symfony\\Component\\Console\\Exception\\InvalidOptionException',
    4 => 'JsonSchema\\Exception\\InvalidArgumentException',
    5 => 'JsonSchema\\Exception\\InvalidSourceUriException',
    6 => 'Dotenv\\Exception\\InvalidCallbackException',
    7 => 'Dotenv\\Exception\\InvalidFileException',
    8 => 'Dotenv\\Exception\\InvalidPathException',
    9 => 'Doctrine\\Instantiator\\Exception\\InvalidArgumentException',
  ),
  'Symfony\\Component\\Process\\Exception\\RuntimeException' => 
  array (
    0 => 'Symfony\\Component\\Process\\Exception\\ProcessFailedException',
    1 => 'Symfony\\Component\\Process\\Exception\\ProcessTimedOutException',
  ),
  'Symfony\\Component\\Process\\Process' => 
  array (
    0 => 'Symfony\\Component\\Process\\PhpProcess',
  ),
  'Symfony\\Component\\Process\\Pipes\\PipesInterface' => 
  array (
    0 => 'Symfony\\Component\\Process\\Pipes\\AbstractPipes',
    1 => 'Symfony\\Component\\Process\\Pipes\\UnixPipes',
    2 => 'Symfony\\Component\\Process\\Pipes\\WindowsPipes',
  ),
  'Symfony\\Component\\Process\\Pipes\\AbstractPipes' => 
  array (
    0 => 'Symfony\\Component\\Process\\Pipes\\UnixPipes',
    1 => 'Symfony\\Component\\Process\\Pipes\\WindowsPipes',
  ),
  'Symfony\\Component\\Finder\\Adapter\\AdapterInterface' => 
  array (
    0 => 'Symfony\\Component\\Finder\\Adapter\\AbstractAdapter',
    1 => 'Symfony\\Component\\Finder\\Adapter\\AbstractFindAdapter',
    2 => 'Symfony\\Component\\Finder\\Adapter\\BsdFindAdapter',
    3 => 'Symfony\\Component\\Finder\\Adapter\\GnuFindAdapter',
    4 => 'Symfony\\Component\\Finder\\Adapter\\PhpAdapter',
  ),
  'Symfony\\Component\\Finder\\Adapter\\AbstractAdapter' => 
  array (
    0 => 'Symfony\\Component\\Finder\\Adapter\\AbstractFindAdapter',
    1 => 'Symfony\\Component\\Finder\\Adapter\\BsdFindAdapter',
    2 => 'Symfony\\Component\\Finder\\Adapter\\GnuFindAdapter',
    3 => 'Symfony\\Component\\Finder\\Adapter\\PhpAdapter',
  ),
  'Symfony\\Component\\Finder\\Adapter\\AbstractFindAdapter' => 
  array (
    0 => 'Symfony\\Component\\Finder\\Adapter\\BsdFindAdapter',
    1 => 'Symfony\\Component\\Finder\\Adapter\\GnuFindAdapter',
  ),
  'Symfony\\Component\\Finder\\Comparator\\Comparator' => 
  array (
    0 => 'Symfony\\Component\\Finder\\Comparator\\DateComparator',
    1 => 'Symfony\\Component\\Finder\\Comparator\\NumberComparator',
  ),
  'UnexpectedValueException' => 
  array (
    0 => 'Symfony\\Component\\Finder\\Exception\\AccessDeniedException',
    1 => 'Doctrine\\Instantiator\\Exception\\UnexpectedValueException',
    2 => 'DeepCopy\\Exception\\CloneException',
  ),
  'Symfony\\Component\\Finder\\Exception\\ExceptionInterface' => 
  array (
    0 => 'Symfony\\Component\\Finder\\Exception\\AdapterFailureException',
    1 => 'Symfony\\Component\\Finder\\Exception\\OperationNotPermitedException',
    2 => 'Symfony\\Component\\Finder\\Exception\\ShellCommandFailureException',
  ),
  'Symfony\\Component\\Finder\\Exception\\AdapterFailureException' => 
  array (
    0 => 'Symfony\\Component\\Finder\\Exception\\OperationNotPermitedException',
    1 => 'Symfony\\Component\\Finder\\Exception\\ShellCommandFailureException',
  ),
  'Symfony\\Component\\Finder\\Expression\\ValueInterface' => 
  array (
    0 => 'Symfony\\Component\\Finder\\Expression\\Expression',
    1 => 'Symfony\\Component\\Finder\\Expression\\Glob',
    2 => 'Symfony\\Component\\Finder\\Expression\\Regex',
  ),
  'Symfony\\Component\\Finder\\Iterator\\FilterIterator' => 
  array (
    0 => 'Symfony\\Component\\Finder\\Iterator\\CustomFilterIterator',
    1 => 'Symfony\\Component\\Finder\\Iterator\\DateRangeFilterIterator',
    2 => 'Symfony\\Component\\Finder\\Iterator\\DepthRangeFilterIterator',
    3 => 'Symfony\\Component\\Finder\\Iterator\\ExcludeDirectoryFilterIterator',
    4 => 'Symfony\\Component\\Finder\\Iterator\\MultiplePcreFilterIterator',
    5 => 'Symfony\\Component\\Finder\\Iterator\\FilecontentFilterIterator',
    6 => 'Symfony\\Component\\Finder\\Iterator\\FilenameFilterIterator',
    7 => 'Symfony\\Component\\Finder\\Iterator\\FileTypeFilterIterator',
    8 => 'Symfony\\Component\\Finder\\Iterator\\PathFilterIterator',
    9 => 'Symfony\\Component\\Finder\\Iterator\\SizeRangeFilterIterator',
  ),
  'Symfony\\Component\\Finder\\Iterator\\MultiplePcreFilterIterator' => 
  array (
    0 => 'Symfony\\Component\\Finder\\Iterator\\FilecontentFilterIterator',
    1 => 'Symfony\\Component\\Finder\\Iterator\\FilenameFilterIterator',
    2 => 'Symfony\\Component\\Finder\\Iterator\\PathFilterIterator',
  ),
  'Symfony\\Component\\Filesystem\\Exception\\IOExceptionInterface' => 
  array (
    0 => 'Symfony\\Component\\Filesystem\\Exception\\IOException',
    1 => 'Symfony\\Component\\Filesystem\\Exception\\FileNotFoundException',
  ),
  'Symfony\\Component\\Filesystem\\Exception\\ExceptionInterface' => 
  array (
    0 => 'Symfony\\Component\\Filesystem\\Exception\\IOException',
    1 => 'Symfony\\Component\\Filesystem\\Exception\\FileNotFoundException',
  ),
  'Symfony\\Component\\Filesystem\\Exception\\IOException' => 
  array (
    0 => 'Symfony\\Component\\Filesystem\\Exception\\FileNotFoundException',
  ),
  'Symfony\\Component\\Console\\Descriptor\\DescriptorInterface' => 
  array (
    0 => 'Symfony\\Component\\Console\\Descriptor\\Descriptor',
    1 => 'Symfony\\Component\\Console\\Descriptor\\JsonDescriptor',
    2 => 'Symfony\\Component\\Console\\Descriptor\\MarkdownDescriptor',
    3 => 'Symfony\\Component\\Console\\Descriptor\\TextDescriptor',
    4 => 'Symfony\\Component\\Console\\Descriptor\\XmlDescriptor',
  ),
  'Symfony\\Component\\Console\\Descriptor\\Descriptor' => 
  array (
    0 => 'Symfony\\Component\\Console\\Descriptor\\JsonDescriptor',
    1 => 'Symfony\\Component\\Console\\Descriptor\\MarkdownDescriptor',
    2 => 'Symfony\\Component\\Console\\Descriptor\\TextDescriptor',
    3 => 'Symfony\\Component\\Console\\Descriptor\\XmlDescriptor',
  ),
  'Symfony\\Component\\Console\\Exception\\ExceptionInterface' => 
  array (
    0 => 'Symfony\\Component\\Console\\Exception\\CommandNotFoundException',
    1 => 'Symfony\\Component\\Console\\Exception\\InvalidArgumentException',
    2 => 'Symfony\\Component\\Console\\Exception\\InvalidOptionException',
    3 => 'Symfony\\Component\\Console\\Exception\\LogicException',
    4 => 'Symfony\\Component\\Console\\Exception\\RuntimeException',
  ),
  'Symfony\\Component\\Console\\Helper\\QuestionHelper' => 
  array (
    0 => 'Symfony\\Component\\Console\\Helper\\SymfonyQuestionHelper',
  ),
  'Symfony\\Component\\Console\\Helper\\TableCell' => 
  array (
    0 => 'Symfony\\Component\\Console\\Helper\\TableSeparator',
  ),
  'Symfony\\Component\\Console\\Input\\ArgvInput' => 
  array (
    0 => 'Symfony\\Component\\Console\\Input\\StringInput',
  ),
  'Symfony\\Component\\Console\\Question\\Question' => 
  array (
    0 => 'Symfony\\Component\\Console\\Question\\ChoiceQuestion',
    1 => 'Symfony\\Component\\Console\\Question\\ConfirmationQuestion',
  ),
  'Symfony\\Component\\Console\\Style\\StyleInterface' => 
  array (
    0 => 'Symfony\\Component\\Console\\Style\\OutputStyle',
    1 => 'Symfony\\Component\\Console\\Style\\SymfonyStyle',
  ),
  'Symfony\\Component\\Console\\Style\\OutputStyle' => 
  array (
    0 => 'Symfony\\Component\\Console\\Style\\SymfonyStyle',
  ),
  'Stecman\\Component\\Symfony\\Console\\BashCompletion\\Completion\\CompletionInterface' => 
  array (
    0 => 'Stecman\\Component\\Symfony\\Console\\BashCompletion\\Completion\\ShellPathCompletion',
    1 => 'Stecman\\Component\\Symfony\\Console\\BashCompletion\\Completion',
  ),
  'Stecman\\Component\\Symfony\\Console\\BashCompletion\\CompletionContext' => 
  array (
    0 => 'Stecman\\Component\\Symfony\\Console\\BashCompletion\\EnvironmentCompletionContext',
  ),
  'Seld\\JsonLint\\ParsingException' => 
  array (
    0 => 'Seld\\JsonLint\\DuplicateKeyException',
  ),
  'PhpParser\\Builder' => 
  array (
    0 => 'PhpParser\\BuilderAbstract',
    1 => 'PhpParser\\Builder\\Declaration',
    2 => 'PhpParser\\Builder\\Class_',
    3 => 'PhpParser\\Builder\\FunctionLike',
    4 => 'PhpParser\\Builder\\Function_',
    5 => 'PhpParser\\Builder\\Interface_',
    6 => 'PhpParser\\Builder\\Method',
    7 => 'PhpParser\\Builder\\Namespace_',
    8 => 'PhpParser\\Builder\\Param',
    9 => 'PhpParser\\Builder\\Property',
    10 => 'PhpParser\\Builder\\Trait_',
    11 => 'PhpParser\\Builder\\Use_',
  ),
  'PhpParser\\BuilderAbstract' => 
  array (
    0 => 'PhpParser\\Builder\\Declaration',
    1 => 'PhpParser\\Builder\\Class_',
    2 => 'PhpParser\\Builder\\FunctionLike',
    3 => 'PhpParser\\Builder\\Function_',
    4 => 'PhpParser\\Builder\\Interface_',
    5 => 'PhpParser\\Builder\\Method',
    6 => 'PhpParser\\Builder\\Namespace_',
    7 => 'PhpParser\\Builder\\Param',
    8 => 'PhpParser\\Builder\\Property',
    9 => 'PhpParser\\Builder\\Trait_',
    10 => 'PhpParser\\Builder\\Use_',
  ),
  'PhpParser\\Builder\\Declaration' => 
  array (
    0 => 'PhpParser\\Builder\\Class_',
    1 => 'PhpParser\\Builder\\FunctionLike',
    2 => 'PhpParser\\Builder\\Function_',
    3 => 'PhpParser\\Builder\\Interface_',
    4 => 'PhpParser\\Builder\\Method',
    5 => 'PhpParser\\Builder\\Trait_',
  ),
  'PhpParser\\Builder\\FunctionLike' => 
  array (
    0 => 'PhpParser\\Builder\\Function_',
    1 => 'PhpParser\\Builder\\Method',
  ),
  'PhpParser\\Comment' => 
  array (
    0 => 'PhpParser\\Comment\\Doc',
  ),
  'PhpParser\\Lexer' => 
  array (
    0 => 'PhpParser\\Lexer\\Emulative',
  ),
  'PhpParser\\Node' => 
  array (
    0 => 'PhpParser\\NodeAbstract',
    1 => 'PhpParser\\Node\\Arg',
    2 => 'PhpParser\\Node\\Const_',
    3 => 'PhpParser\\Node\\Expr',
    4 => 'PhpParser\\Node\\Expr\\Array_',
    5 => 'PhpParser\\Node\\Expr\\ArrayDimFetch',
    6 => 'PhpParser\\Node\\Expr\\ArrayItem',
    7 => 'PhpParser\\Node\\Expr\\Assign',
    8 => 'PhpParser\\Node\\Expr\\AssignOp',
    9 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseAnd',
    10 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseOr',
    11 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseXor',
    12 => 'PhpParser\\Node\\Expr\\AssignOp\\Concat',
    13 => 'PhpParser\\Node\\Expr\\AssignOp\\Div',
    14 => 'PhpParser\\Node\\Expr\\AssignOp\\Minus',
    15 => 'PhpParser\\Node\\Expr\\AssignOp\\Mod',
    16 => 'PhpParser\\Node\\Expr\\AssignOp\\Mul',
    17 => 'PhpParser\\Node\\Expr\\AssignOp\\Plus',
    18 => 'PhpParser\\Node\\Expr\\AssignOp\\Pow',
    19 => 'PhpParser\\Node\\Expr\\AssignOp\\ShiftLeft',
    20 => 'PhpParser\\Node\\Expr\\AssignOp\\ShiftRight',
    21 => 'PhpParser\\Node\\Expr\\AssignRef',
    22 => 'PhpParser\\Node\\Expr\\BinaryOp',
    23 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseAnd',
    24 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseOr',
    25 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseXor',
    26 => 'PhpParser\\Node\\Expr\\BinaryOp\\BooleanAnd',
    27 => 'PhpParser\\Node\\Expr\\BinaryOp\\BooleanOr',
    28 => 'PhpParser\\Node\\Expr\\BinaryOp\\Coalesce',
    29 => 'PhpParser\\Node\\Expr\\BinaryOp\\Concat',
    30 => 'PhpParser\\Node\\Expr\\BinaryOp\\Div',
    31 => 'PhpParser\\Node\\Expr\\BinaryOp\\Equal',
    32 => 'PhpParser\\Node\\Expr\\BinaryOp\\Greater',
    33 => 'PhpParser\\Node\\Expr\\BinaryOp\\GreaterOrEqual',
    34 => 'PhpParser\\Node\\Expr\\BinaryOp\\Identical',
    35 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalAnd',
    36 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalOr',
    37 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalXor',
    38 => 'PhpParser\\Node\\Expr\\BinaryOp\\Minus',
    39 => 'PhpParser\\Node\\Expr\\BinaryOp\\Mod',
    40 => 'PhpParser\\Node\\Expr\\BinaryOp\\Mul',
    41 => 'PhpParser\\Node\\Expr\\BinaryOp\\NotEqual',
    42 => 'PhpParser\\Node\\Expr\\BinaryOp\\NotIdentical',
    43 => 'PhpParser\\Node\\Expr\\BinaryOp\\Plus',
    44 => 'PhpParser\\Node\\Expr\\BinaryOp\\Pow',
    45 => 'PhpParser\\Node\\Expr\\BinaryOp\\ShiftLeft',
    46 => 'PhpParser\\Node\\Expr\\BinaryOp\\ShiftRight',
    47 => 'PhpParser\\Node\\Expr\\BinaryOp\\Smaller',
    48 => 'PhpParser\\Node\\Expr\\BinaryOp\\SmallerOrEqual',
    49 => 'PhpParser\\Node\\Expr\\BinaryOp\\Spaceship',
    50 => 'PhpParser\\Node\\Expr\\BitwiseNot',
    51 => 'PhpParser\\Node\\Expr\\BooleanNot',
    52 => 'PhpParser\\Node\\Expr\\Cast',
    53 => 'PhpParser\\Node\\Expr\\Cast\\Array_',
    54 => 'PhpParser\\Node\\Expr\\Cast\\Bool_',
    55 => 'PhpParser\\Node\\Expr\\Cast\\Double',
    56 => 'PhpParser\\Node\\Expr\\Cast\\Int_',
    57 => 'PhpParser\\Node\\Expr\\Cast\\Object_',
    58 => 'PhpParser\\Node\\Expr\\Cast\\String_',
    59 => 'PhpParser\\Node\\Expr\\Cast\\Unset_',
    60 => 'PhpParser\\Node\\Expr\\ClassConstFetch',
    61 => 'PhpParser\\Node\\Expr\\Clone_',
    62 => 'PhpParser\\Node\\Expr\\Closure',
    63 => 'PhpParser\\Node\\Expr\\ClosureUse',
    64 => 'PhpParser\\Node\\Expr\\ConstFetch',
    65 => 'PhpParser\\Node\\Expr\\Empty_',
    66 => 'PhpParser\\Node\\Expr\\ErrorSuppress',
    67 => 'PhpParser\\Node\\Expr\\Eval_',
    68 => 'PhpParser\\Node\\Expr\\Exit_',
    69 => 'PhpParser\\Node\\Expr\\FuncCall',
    70 => 'PhpParser\\Node\\Expr\\Include_',
    71 => 'PhpParser\\Node\\Expr\\Instanceof_',
    72 => 'PhpParser\\Node\\Expr\\Isset_',
    73 => 'PhpParser\\Node\\Expr\\List_',
    74 => 'PhpParser\\Node\\Expr\\MethodCall',
    75 => 'PhpParser\\Node\\Expr\\New_',
    76 => 'PhpParser\\Node\\Expr\\PostDec',
    77 => 'PhpParser\\Node\\Expr\\PostInc',
    78 => 'PhpParser\\Node\\Expr\\PreDec',
    79 => 'PhpParser\\Node\\Expr\\PreInc',
    80 => 'PhpParser\\Node\\Expr\\Print_',
    81 => 'PhpParser\\Node\\Expr\\PropertyFetch',
    82 => 'PhpParser\\Node\\Expr\\ShellExec',
    83 => 'PhpParser\\Node\\Expr\\StaticCall',
    84 => 'PhpParser\\Node\\Expr\\StaticPropertyFetch',
    85 => 'PhpParser\\Node\\Expr\\Ternary',
    86 => 'PhpParser\\Node\\Expr\\UnaryMinus',
    87 => 'PhpParser\\Node\\Expr\\UnaryPlus',
    88 => 'PhpParser\\Node\\Expr\\Variable',
    89 => 'PhpParser\\Node\\Expr\\Yield_',
    90 => 'PhpParser\\Node\\Expr\\YieldFrom',
    91 => 'PhpParser\\Node\\Name',
    92 => 'PhpParser\\Node\\Name\\FullyQualified',
    93 => 'PhpParser\\Node\\Name\\Relative',
    94 => 'PhpParser\\Node\\Param',
    95 => 'PhpParser\\Node\\Scalar',
    96 => 'PhpParser\\Node\\Scalar\\DNumber',
    97 => 'PhpParser\\Node\\Scalar\\Encapsed',
    98 => 'PhpParser\\Node\\Scalar\\EncapsedStringPart',
    99 => 'PhpParser\\Node\\Scalar\\LNumber',
    100 => 'PhpParser\\Node\\Scalar\\MagicConst',
    101 => 'PhpParser\\Node\\Scalar\\MagicConst\\Class_',
    102 => 'PhpParser\\Node\\Scalar\\MagicConst\\Dir',
    103 => 'PhpParser\\Node\\Scalar\\MagicConst\\File',
    104 => 'PhpParser\\Node\\Scalar\\MagicConst\\Function_',
    105 => 'PhpParser\\Node\\Scalar\\MagicConst\\Line',
    106 => 'PhpParser\\Node\\Scalar\\MagicConst\\Method',
    107 => 'PhpParser\\Node\\Scalar\\MagicConst\\Namespace_',
    108 => 'PhpParser\\Node\\Scalar\\MagicConst\\Trait_',
    109 => 'PhpParser\\Node\\Scalar\\String_',
    110 => 'PhpParser\\Node\\Stmt',
    111 => 'PhpParser\\Node\\Stmt\\Break_',
    112 => 'PhpParser\\Node\\Stmt\\Case_',
    113 => 'PhpParser\\Node\\Stmt\\Catch_',
    114 => 'PhpParser\\Node\\Stmt\\ClassLike',
    115 => 'PhpParser\\Node\\Stmt\\Class_',
    116 => 'PhpParser\\Node\\Stmt\\ClassConst',
    117 => 'PhpParser\\Node\\Stmt\\ClassMethod',
    118 => 'PhpParser\\Node\\Stmt\\Const_',
    119 => 'PhpParser\\Node\\Stmt\\Continue_',
    120 => 'PhpParser\\Node\\Stmt\\Declare_',
    121 => 'PhpParser\\Node\\Stmt\\DeclareDeclare',
    122 => 'PhpParser\\Node\\Stmt\\Do_',
    123 => 'PhpParser\\Node\\Stmt\\Echo_',
    124 => 'PhpParser\\Node\\Stmt\\Else_',
    125 => 'PhpParser\\Node\\Stmt\\ElseIf_',
    126 => 'PhpParser\\Node\\Stmt\\For_',
    127 => 'PhpParser\\Node\\Stmt\\Foreach_',
    128 => 'PhpParser\\Node\\Stmt\\Function_',
    129 => 'PhpParser\\Node\\Stmt\\Global_',
    130 => 'PhpParser\\Node\\Stmt\\Goto_',
    131 => 'PhpParser\\Node\\Stmt\\GroupUse',
    132 => 'PhpParser\\Node\\Stmt\\HaltCompiler',
    133 => 'PhpParser\\Node\\Stmt\\If_',
    134 => 'PhpParser\\Node\\Stmt\\InlineHTML',
    135 => 'PhpParser\\Node\\Stmt\\Interface_',
    136 => 'PhpParser\\Node\\Stmt\\Label',
    137 => 'PhpParser\\Node\\Stmt\\Namespace_',
    138 => 'PhpParser\\Node\\Stmt\\Nop',
    139 => 'PhpParser\\Node\\Stmt\\Property',
    140 => 'PhpParser\\Node\\Stmt\\PropertyProperty',
    141 => 'PhpParser\\Node\\Stmt\\Return_',
    142 => 'PhpParser\\Node\\Stmt\\Static_',
    143 => 'PhpParser\\Node\\Stmt\\StaticVar',
    144 => 'PhpParser\\Node\\Stmt\\Switch_',
    145 => 'PhpParser\\Node\\Stmt\\Throw_',
    146 => 'PhpParser\\Node\\Stmt\\Trait_',
    147 => 'PhpParser\\Node\\Stmt\\TraitUse',
    148 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation',
    149 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation\\Alias',
    150 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation\\Precedence',
    151 => 'PhpParser\\Node\\Stmt\\TryCatch',
    152 => 'PhpParser\\Node\\Stmt\\Unset_',
    153 => 'PhpParser\\Node\\Stmt\\Use_',
    154 => 'PhpParser\\Node\\Stmt\\UseUse',
    155 => 'PhpParser\\Node\\Stmt\\While_',
  ),
  'PhpParser\\NodeAbstract' => 
  array (
    0 => 'PhpParser\\Node\\Arg',
    1 => 'PhpParser\\Node\\Const_',
    2 => 'PhpParser\\Node\\Expr',
    3 => 'PhpParser\\Node\\Expr\\Array_',
    4 => 'PhpParser\\Node\\Expr\\ArrayDimFetch',
    5 => 'PhpParser\\Node\\Expr\\ArrayItem',
    6 => 'PhpParser\\Node\\Expr\\Assign',
    7 => 'PhpParser\\Node\\Expr\\AssignOp',
    8 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseAnd',
    9 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseOr',
    10 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseXor',
    11 => 'PhpParser\\Node\\Expr\\AssignOp\\Concat',
    12 => 'PhpParser\\Node\\Expr\\AssignOp\\Div',
    13 => 'PhpParser\\Node\\Expr\\AssignOp\\Minus',
    14 => 'PhpParser\\Node\\Expr\\AssignOp\\Mod',
    15 => 'PhpParser\\Node\\Expr\\AssignOp\\Mul',
    16 => 'PhpParser\\Node\\Expr\\AssignOp\\Plus',
    17 => 'PhpParser\\Node\\Expr\\AssignOp\\Pow',
    18 => 'PhpParser\\Node\\Expr\\AssignOp\\ShiftLeft',
    19 => 'PhpParser\\Node\\Expr\\AssignOp\\ShiftRight',
    20 => 'PhpParser\\Node\\Expr\\AssignRef',
    21 => 'PhpParser\\Node\\Expr\\BinaryOp',
    22 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseAnd',
    23 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseOr',
    24 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseXor',
    25 => 'PhpParser\\Node\\Expr\\BinaryOp\\BooleanAnd',
    26 => 'PhpParser\\Node\\Expr\\BinaryOp\\BooleanOr',
    27 => 'PhpParser\\Node\\Expr\\BinaryOp\\Coalesce',
    28 => 'PhpParser\\Node\\Expr\\BinaryOp\\Concat',
    29 => 'PhpParser\\Node\\Expr\\BinaryOp\\Div',
    30 => 'PhpParser\\Node\\Expr\\BinaryOp\\Equal',
    31 => 'PhpParser\\Node\\Expr\\BinaryOp\\Greater',
    32 => 'PhpParser\\Node\\Expr\\BinaryOp\\GreaterOrEqual',
    33 => 'PhpParser\\Node\\Expr\\BinaryOp\\Identical',
    34 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalAnd',
    35 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalOr',
    36 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalXor',
    37 => 'PhpParser\\Node\\Expr\\BinaryOp\\Minus',
    38 => 'PhpParser\\Node\\Expr\\BinaryOp\\Mod',
    39 => 'PhpParser\\Node\\Expr\\BinaryOp\\Mul',
    40 => 'PhpParser\\Node\\Expr\\BinaryOp\\NotEqual',
    41 => 'PhpParser\\Node\\Expr\\BinaryOp\\NotIdentical',
    42 => 'PhpParser\\Node\\Expr\\BinaryOp\\Plus',
    43 => 'PhpParser\\Node\\Expr\\BinaryOp\\Pow',
    44 => 'PhpParser\\Node\\Expr\\BinaryOp\\ShiftLeft',
    45 => 'PhpParser\\Node\\Expr\\BinaryOp\\ShiftRight',
    46 => 'PhpParser\\Node\\Expr\\BinaryOp\\Smaller',
    47 => 'PhpParser\\Node\\Expr\\BinaryOp\\SmallerOrEqual',
    48 => 'PhpParser\\Node\\Expr\\BinaryOp\\Spaceship',
    49 => 'PhpParser\\Node\\Expr\\BitwiseNot',
    50 => 'PhpParser\\Node\\Expr\\BooleanNot',
    51 => 'PhpParser\\Node\\Expr\\Cast',
    52 => 'PhpParser\\Node\\Expr\\Cast\\Array_',
    53 => 'PhpParser\\Node\\Expr\\Cast\\Bool_',
    54 => 'PhpParser\\Node\\Expr\\Cast\\Double',
    55 => 'PhpParser\\Node\\Expr\\Cast\\Int_',
    56 => 'PhpParser\\Node\\Expr\\Cast\\Object_',
    57 => 'PhpParser\\Node\\Expr\\Cast\\String_',
    58 => 'PhpParser\\Node\\Expr\\Cast\\Unset_',
    59 => 'PhpParser\\Node\\Expr\\ClassConstFetch',
    60 => 'PhpParser\\Node\\Expr\\Clone_',
    61 => 'PhpParser\\Node\\Expr\\Closure',
    62 => 'PhpParser\\Node\\Expr\\ClosureUse',
    63 => 'PhpParser\\Node\\Expr\\ConstFetch',
    64 => 'PhpParser\\Node\\Expr\\Empty_',
    65 => 'PhpParser\\Node\\Expr\\ErrorSuppress',
    66 => 'PhpParser\\Node\\Expr\\Eval_',
    67 => 'PhpParser\\Node\\Expr\\Exit_',
    68 => 'PhpParser\\Node\\Expr\\FuncCall',
    69 => 'PhpParser\\Node\\Expr\\Include_',
    70 => 'PhpParser\\Node\\Expr\\Instanceof_',
    71 => 'PhpParser\\Node\\Expr\\Isset_',
    72 => 'PhpParser\\Node\\Expr\\List_',
    73 => 'PhpParser\\Node\\Expr\\MethodCall',
    74 => 'PhpParser\\Node\\Expr\\New_',
    75 => 'PhpParser\\Node\\Expr\\PostDec',
    76 => 'PhpParser\\Node\\Expr\\PostInc',
    77 => 'PhpParser\\Node\\Expr\\PreDec',
    78 => 'PhpParser\\Node\\Expr\\PreInc',
    79 => 'PhpParser\\Node\\Expr\\Print_',
    80 => 'PhpParser\\Node\\Expr\\PropertyFetch',
    81 => 'PhpParser\\Node\\Expr\\ShellExec',
    82 => 'PhpParser\\Node\\Expr\\StaticCall',
    83 => 'PhpParser\\Node\\Expr\\StaticPropertyFetch',
    84 => 'PhpParser\\Node\\Expr\\Ternary',
    85 => 'PhpParser\\Node\\Expr\\UnaryMinus',
    86 => 'PhpParser\\Node\\Expr\\UnaryPlus',
    87 => 'PhpParser\\Node\\Expr\\Variable',
    88 => 'PhpParser\\Node\\Expr\\Yield_',
    89 => 'PhpParser\\Node\\Expr\\YieldFrom',
    90 => 'PhpParser\\Node\\Name',
    91 => 'PhpParser\\Node\\Name\\FullyQualified',
    92 => 'PhpParser\\Node\\Name\\Relative',
    93 => 'PhpParser\\Node\\Param',
    94 => 'PhpParser\\Node\\Scalar',
    95 => 'PhpParser\\Node\\Scalar\\DNumber',
    96 => 'PhpParser\\Node\\Scalar\\Encapsed',
    97 => 'PhpParser\\Node\\Scalar\\EncapsedStringPart',
    98 => 'PhpParser\\Node\\Scalar\\LNumber',
    99 => 'PhpParser\\Node\\Scalar\\MagicConst',
    100 => 'PhpParser\\Node\\Scalar\\MagicConst\\Class_',
    101 => 'PhpParser\\Node\\Scalar\\MagicConst\\Dir',
    102 => 'PhpParser\\Node\\Scalar\\MagicConst\\File',
    103 => 'PhpParser\\Node\\Scalar\\MagicConst\\Function_',
    104 => 'PhpParser\\Node\\Scalar\\MagicConst\\Line',
    105 => 'PhpParser\\Node\\Scalar\\MagicConst\\Method',
    106 => 'PhpParser\\Node\\Scalar\\MagicConst\\Namespace_',
    107 => 'PhpParser\\Node\\Scalar\\MagicConst\\Trait_',
    108 => 'PhpParser\\Node\\Scalar\\String_',
    109 => 'PhpParser\\Node\\Stmt',
    110 => 'PhpParser\\Node\\Stmt\\Break_',
    111 => 'PhpParser\\Node\\Stmt\\Case_',
    112 => 'PhpParser\\Node\\Stmt\\Catch_',
    113 => 'PhpParser\\Node\\Stmt\\ClassLike',
    114 => 'PhpParser\\Node\\Stmt\\Class_',
    115 => 'PhpParser\\Node\\Stmt\\ClassConst',
    116 => 'PhpParser\\Node\\Stmt\\ClassMethod',
    117 => 'PhpParser\\Node\\Stmt\\Const_',
    118 => 'PhpParser\\Node\\Stmt\\Continue_',
    119 => 'PhpParser\\Node\\Stmt\\Declare_',
    120 => 'PhpParser\\Node\\Stmt\\DeclareDeclare',
    121 => 'PhpParser\\Node\\Stmt\\Do_',
    122 => 'PhpParser\\Node\\Stmt\\Echo_',
    123 => 'PhpParser\\Node\\Stmt\\Else_',
    124 => 'PhpParser\\Node\\Stmt\\ElseIf_',
    125 => 'PhpParser\\Node\\Stmt\\For_',
    126 => 'PhpParser\\Node\\Stmt\\Foreach_',
    127 => 'PhpParser\\Node\\Stmt\\Function_',
    128 => 'PhpParser\\Node\\Stmt\\Global_',
    129 => 'PhpParser\\Node\\Stmt\\Goto_',
    130 => 'PhpParser\\Node\\Stmt\\GroupUse',
    131 => 'PhpParser\\Node\\Stmt\\HaltCompiler',
    132 => 'PhpParser\\Node\\Stmt\\If_',
    133 => 'PhpParser\\Node\\Stmt\\InlineHTML',
    134 => 'PhpParser\\Node\\Stmt\\Interface_',
    135 => 'PhpParser\\Node\\Stmt\\Label',
    136 => 'PhpParser\\Node\\Stmt\\Namespace_',
    137 => 'PhpParser\\Node\\Stmt\\Nop',
    138 => 'PhpParser\\Node\\Stmt\\Property',
    139 => 'PhpParser\\Node\\Stmt\\PropertyProperty',
    140 => 'PhpParser\\Node\\Stmt\\Return_',
    141 => 'PhpParser\\Node\\Stmt\\Static_',
    142 => 'PhpParser\\Node\\Stmt\\StaticVar',
    143 => 'PhpParser\\Node\\Stmt\\Switch_',
    144 => 'PhpParser\\Node\\Stmt\\Throw_',
    145 => 'PhpParser\\Node\\Stmt\\Trait_',
    146 => 'PhpParser\\Node\\Stmt\\TraitUse',
    147 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation',
    148 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation\\Alias',
    149 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation\\Precedence',
    150 => 'PhpParser\\Node\\Stmt\\TryCatch',
    151 => 'PhpParser\\Node\\Stmt\\Unset_',
    152 => 'PhpParser\\Node\\Stmt\\Use_',
    153 => 'PhpParser\\Node\\Stmt\\UseUse',
    154 => 'PhpParser\\Node\\Stmt\\While_',
  ),
  'PhpParser\\Node\\Expr' => 
  array (
    0 => 'PhpParser\\Node\\Expr\\Array_',
    1 => 'PhpParser\\Node\\Expr\\ArrayDimFetch',
    2 => 'PhpParser\\Node\\Expr\\ArrayItem',
    3 => 'PhpParser\\Node\\Expr\\Assign',
    4 => 'PhpParser\\Node\\Expr\\AssignOp',
    5 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseAnd',
    6 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseOr',
    7 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseXor',
    8 => 'PhpParser\\Node\\Expr\\AssignOp\\Concat',
    9 => 'PhpParser\\Node\\Expr\\AssignOp\\Div',
    10 => 'PhpParser\\Node\\Expr\\AssignOp\\Minus',
    11 => 'PhpParser\\Node\\Expr\\AssignOp\\Mod',
    12 => 'PhpParser\\Node\\Expr\\AssignOp\\Mul',
    13 => 'PhpParser\\Node\\Expr\\AssignOp\\Plus',
    14 => 'PhpParser\\Node\\Expr\\AssignOp\\Pow',
    15 => 'PhpParser\\Node\\Expr\\AssignOp\\ShiftLeft',
    16 => 'PhpParser\\Node\\Expr\\AssignOp\\ShiftRight',
    17 => 'PhpParser\\Node\\Expr\\AssignRef',
    18 => 'PhpParser\\Node\\Expr\\BinaryOp',
    19 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseAnd',
    20 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseOr',
    21 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseXor',
    22 => 'PhpParser\\Node\\Expr\\BinaryOp\\BooleanAnd',
    23 => 'PhpParser\\Node\\Expr\\BinaryOp\\BooleanOr',
    24 => 'PhpParser\\Node\\Expr\\BinaryOp\\Coalesce',
    25 => 'PhpParser\\Node\\Expr\\BinaryOp\\Concat',
    26 => 'PhpParser\\Node\\Expr\\BinaryOp\\Div',
    27 => 'PhpParser\\Node\\Expr\\BinaryOp\\Equal',
    28 => 'PhpParser\\Node\\Expr\\BinaryOp\\Greater',
    29 => 'PhpParser\\Node\\Expr\\BinaryOp\\GreaterOrEqual',
    30 => 'PhpParser\\Node\\Expr\\BinaryOp\\Identical',
    31 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalAnd',
    32 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalOr',
    33 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalXor',
    34 => 'PhpParser\\Node\\Expr\\BinaryOp\\Minus',
    35 => 'PhpParser\\Node\\Expr\\BinaryOp\\Mod',
    36 => 'PhpParser\\Node\\Expr\\BinaryOp\\Mul',
    37 => 'PhpParser\\Node\\Expr\\BinaryOp\\NotEqual',
    38 => 'PhpParser\\Node\\Expr\\BinaryOp\\NotIdentical',
    39 => 'PhpParser\\Node\\Expr\\BinaryOp\\Plus',
    40 => 'PhpParser\\Node\\Expr\\BinaryOp\\Pow',
    41 => 'PhpParser\\Node\\Expr\\BinaryOp\\ShiftLeft',
    42 => 'PhpParser\\Node\\Expr\\BinaryOp\\ShiftRight',
    43 => 'PhpParser\\Node\\Expr\\BinaryOp\\Smaller',
    44 => 'PhpParser\\Node\\Expr\\BinaryOp\\SmallerOrEqual',
    45 => 'PhpParser\\Node\\Expr\\BinaryOp\\Spaceship',
    46 => 'PhpParser\\Node\\Expr\\BitwiseNot',
    47 => 'PhpParser\\Node\\Expr\\BooleanNot',
    48 => 'PhpParser\\Node\\Expr\\Cast',
    49 => 'PhpParser\\Node\\Expr\\Cast\\Array_',
    50 => 'PhpParser\\Node\\Expr\\Cast\\Bool_',
    51 => 'PhpParser\\Node\\Expr\\Cast\\Double',
    52 => 'PhpParser\\Node\\Expr\\Cast\\Int_',
    53 => 'PhpParser\\Node\\Expr\\Cast\\Object_',
    54 => 'PhpParser\\Node\\Expr\\Cast\\String_',
    55 => 'PhpParser\\Node\\Expr\\Cast\\Unset_',
    56 => 'PhpParser\\Node\\Expr\\ClassConstFetch',
    57 => 'PhpParser\\Node\\Expr\\Clone_',
    58 => 'PhpParser\\Node\\Expr\\Closure',
    59 => 'PhpParser\\Node\\Expr\\ClosureUse',
    60 => 'PhpParser\\Node\\Expr\\ConstFetch',
    61 => 'PhpParser\\Node\\Expr\\Empty_',
    62 => 'PhpParser\\Node\\Expr\\ErrorSuppress',
    63 => 'PhpParser\\Node\\Expr\\Eval_',
    64 => 'PhpParser\\Node\\Expr\\Exit_',
    65 => 'PhpParser\\Node\\Expr\\FuncCall',
    66 => 'PhpParser\\Node\\Expr\\Include_',
    67 => 'PhpParser\\Node\\Expr\\Instanceof_',
    68 => 'PhpParser\\Node\\Expr\\Isset_',
    69 => 'PhpParser\\Node\\Expr\\List_',
    70 => 'PhpParser\\Node\\Expr\\MethodCall',
    71 => 'PhpParser\\Node\\Expr\\New_',
    72 => 'PhpParser\\Node\\Expr\\PostDec',
    73 => 'PhpParser\\Node\\Expr\\PostInc',
    74 => 'PhpParser\\Node\\Expr\\PreDec',
    75 => 'PhpParser\\Node\\Expr\\PreInc',
    76 => 'PhpParser\\Node\\Expr\\Print_',
    77 => 'PhpParser\\Node\\Expr\\PropertyFetch',
    78 => 'PhpParser\\Node\\Expr\\ShellExec',
    79 => 'PhpParser\\Node\\Expr\\StaticCall',
    80 => 'PhpParser\\Node\\Expr\\StaticPropertyFetch',
    81 => 'PhpParser\\Node\\Expr\\Ternary',
    82 => 'PhpParser\\Node\\Expr\\UnaryMinus',
    83 => 'PhpParser\\Node\\Expr\\UnaryPlus',
    84 => 'PhpParser\\Node\\Expr\\Variable',
    85 => 'PhpParser\\Node\\Expr\\Yield_',
    86 => 'PhpParser\\Node\\Expr\\YieldFrom',
    87 => 'PhpParser\\Node\\Scalar',
    88 => 'PhpParser\\Node\\Scalar\\DNumber',
    89 => 'PhpParser\\Node\\Scalar\\Encapsed',
    90 => 'PhpParser\\Node\\Scalar\\EncapsedStringPart',
    91 => 'PhpParser\\Node\\Scalar\\LNumber',
    92 => 'PhpParser\\Node\\Scalar\\MagicConst',
    93 => 'PhpParser\\Node\\Scalar\\MagicConst\\Class_',
    94 => 'PhpParser\\Node\\Scalar\\MagicConst\\Dir',
    95 => 'PhpParser\\Node\\Scalar\\MagicConst\\File',
    96 => 'PhpParser\\Node\\Scalar\\MagicConst\\Function_',
    97 => 'PhpParser\\Node\\Scalar\\MagicConst\\Line',
    98 => 'PhpParser\\Node\\Scalar\\MagicConst\\Method',
    99 => 'PhpParser\\Node\\Scalar\\MagicConst\\Namespace_',
    100 => 'PhpParser\\Node\\Scalar\\MagicConst\\Trait_',
    101 => 'PhpParser\\Node\\Scalar\\String_',
  ),
  'PhpParser\\Node\\Expr\\AssignOp' => 
  array (
    0 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseAnd',
    1 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseOr',
    2 => 'PhpParser\\Node\\Expr\\AssignOp\\BitwiseXor',
    3 => 'PhpParser\\Node\\Expr\\AssignOp\\Concat',
    4 => 'PhpParser\\Node\\Expr\\AssignOp\\Div',
    5 => 'PhpParser\\Node\\Expr\\AssignOp\\Minus',
    6 => 'PhpParser\\Node\\Expr\\AssignOp\\Mod',
    7 => 'PhpParser\\Node\\Expr\\AssignOp\\Mul',
    8 => 'PhpParser\\Node\\Expr\\AssignOp\\Plus',
    9 => 'PhpParser\\Node\\Expr\\AssignOp\\Pow',
    10 => 'PhpParser\\Node\\Expr\\AssignOp\\ShiftLeft',
    11 => 'PhpParser\\Node\\Expr\\AssignOp\\ShiftRight',
  ),
  'PhpParser\\Node\\Expr\\BinaryOp' => 
  array (
    0 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseAnd',
    1 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseOr',
    2 => 'PhpParser\\Node\\Expr\\BinaryOp\\BitwiseXor',
    3 => 'PhpParser\\Node\\Expr\\BinaryOp\\BooleanAnd',
    4 => 'PhpParser\\Node\\Expr\\BinaryOp\\BooleanOr',
    5 => 'PhpParser\\Node\\Expr\\BinaryOp\\Coalesce',
    6 => 'PhpParser\\Node\\Expr\\BinaryOp\\Concat',
    7 => 'PhpParser\\Node\\Expr\\BinaryOp\\Div',
    8 => 'PhpParser\\Node\\Expr\\BinaryOp\\Equal',
    9 => 'PhpParser\\Node\\Expr\\BinaryOp\\Greater',
    10 => 'PhpParser\\Node\\Expr\\BinaryOp\\GreaterOrEqual',
    11 => 'PhpParser\\Node\\Expr\\BinaryOp\\Identical',
    12 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalAnd',
    13 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalOr',
    14 => 'PhpParser\\Node\\Expr\\BinaryOp\\LogicalXor',
    15 => 'PhpParser\\Node\\Expr\\BinaryOp\\Minus',
    16 => 'PhpParser\\Node\\Expr\\BinaryOp\\Mod',
    17 => 'PhpParser\\Node\\Expr\\BinaryOp\\Mul',
    18 => 'PhpParser\\Node\\Expr\\BinaryOp\\NotEqual',
    19 => 'PhpParser\\Node\\Expr\\BinaryOp\\NotIdentical',
    20 => 'PhpParser\\Node\\Expr\\BinaryOp\\Plus',
    21 => 'PhpParser\\Node\\Expr\\BinaryOp\\Pow',
    22 => 'PhpParser\\Node\\Expr\\BinaryOp\\ShiftLeft',
    23 => 'PhpParser\\Node\\Expr\\BinaryOp\\ShiftRight',
    24 => 'PhpParser\\Node\\Expr\\BinaryOp\\Smaller',
    25 => 'PhpParser\\Node\\Expr\\BinaryOp\\SmallerOrEqual',
    26 => 'PhpParser\\Node\\Expr\\BinaryOp\\Spaceship',
  ),
  'PhpParser\\Node\\Expr\\Cast' => 
  array (
    0 => 'PhpParser\\Node\\Expr\\Cast\\Array_',
    1 => 'PhpParser\\Node\\Expr\\Cast\\Bool_',
    2 => 'PhpParser\\Node\\Expr\\Cast\\Double',
    3 => 'PhpParser\\Node\\Expr\\Cast\\Int_',
    4 => 'PhpParser\\Node\\Expr\\Cast\\Object_',
    5 => 'PhpParser\\Node\\Expr\\Cast\\String_',
    6 => 'PhpParser\\Node\\Expr\\Cast\\Unset_',
  ),
  'PhpParser\\Node\\FunctionLike' => 
  array (
    0 => 'PhpParser\\Node\\Expr\\Closure',
    1 => 'PhpParser\\Node\\Stmt\\ClassMethod',
    2 => 'PhpParser\\Node\\Stmt\\Function_',
  ),
  'PhpParser\\Node\\Name' => 
  array (
    0 => 'PhpParser\\Node\\Name\\FullyQualified',
    1 => 'PhpParser\\Node\\Name\\Relative',
  ),
  'PhpParser\\Node\\Scalar' => 
  array (
    0 => 'PhpParser\\Node\\Scalar\\DNumber',
    1 => 'PhpParser\\Node\\Scalar\\Encapsed',
    2 => 'PhpParser\\Node\\Scalar\\EncapsedStringPart',
    3 => 'PhpParser\\Node\\Scalar\\LNumber',
    4 => 'PhpParser\\Node\\Scalar\\MagicConst',
    5 => 'PhpParser\\Node\\Scalar\\MagicConst\\Class_',
    6 => 'PhpParser\\Node\\Scalar\\MagicConst\\Dir',
    7 => 'PhpParser\\Node\\Scalar\\MagicConst\\File',
    8 => 'PhpParser\\Node\\Scalar\\MagicConst\\Function_',
    9 => 'PhpParser\\Node\\Scalar\\MagicConst\\Line',
    10 => 'PhpParser\\Node\\Scalar\\MagicConst\\Method',
    11 => 'PhpParser\\Node\\Scalar\\MagicConst\\Namespace_',
    12 => 'PhpParser\\Node\\Scalar\\MagicConst\\Trait_',
    13 => 'PhpParser\\Node\\Scalar\\String_',
  ),
  'PhpParser\\Node\\Scalar\\MagicConst' => 
  array (
    0 => 'PhpParser\\Node\\Scalar\\MagicConst\\Class_',
    1 => 'PhpParser\\Node\\Scalar\\MagicConst\\Dir',
    2 => 'PhpParser\\Node\\Scalar\\MagicConst\\File',
    3 => 'PhpParser\\Node\\Scalar\\MagicConst\\Function_',
    4 => 'PhpParser\\Node\\Scalar\\MagicConst\\Line',
    5 => 'PhpParser\\Node\\Scalar\\MagicConst\\Method',
    6 => 'PhpParser\\Node\\Scalar\\MagicConst\\Namespace_',
    7 => 'PhpParser\\Node\\Scalar\\MagicConst\\Trait_',
  ),
  'PhpParser\\Node\\Stmt' => 
  array (
    0 => 'PhpParser\\Node\\Stmt\\Break_',
    1 => 'PhpParser\\Node\\Stmt\\Case_',
    2 => 'PhpParser\\Node\\Stmt\\Catch_',
    3 => 'PhpParser\\Node\\Stmt\\ClassLike',
    4 => 'PhpParser\\Node\\Stmt\\Class_',
    5 => 'PhpParser\\Node\\Stmt\\ClassConst',
    6 => 'PhpParser\\Node\\Stmt\\ClassMethod',
    7 => 'PhpParser\\Node\\Stmt\\Const_',
    8 => 'PhpParser\\Node\\Stmt\\Continue_',
    9 => 'PhpParser\\Node\\Stmt\\Declare_',
    10 => 'PhpParser\\Node\\Stmt\\DeclareDeclare',
    11 => 'PhpParser\\Node\\Stmt\\Do_',
    12 => 'PhpParser\\Node\\Stmt\\Echo_',
    13 => 'PhpParser\\Node\\Stmt\\Else_',
    14 => 'PhpParser\\Node\\Stmt\\ElseIf_',
    15 => 'PhpParser\\Node\\Stmt\\For_',
    16 => 'PhpParser\\Node\\Stmt\\Foreach_',
    17 => 'PhpParser\\Node\\Stmt\\Function_',
    18 => 'PhpParser\\Node\\Stmt\\Global_',
    19 => 'PhpParser\\Node\\Stmt\\Goto_',
    20 => 'PhpParser\\Node\\Stmt\\GroupUse',
    21 => 'PhpParser\\Node\\Stmt\\HaltCompiler',
    22 => 'PhpParser\\Node\\Stmt\\If_',
    23 => 'PhpParser\\Node\\Stmt\\InlineHTML',
    24 => 'PhpParser\\Node\\Stmt\\Interface_',
    25 => 'PhpParser\\Node\\Stmt\\Label',
    26 => 'PhpParser\\Node\\Stmt\\Namespace_',
    27 => 'PhpParser\\Node\\Stmt\\Nop',
    28 => 'PhpParser\\Node\\Stmt\\Property',
    29 => 'PhpParser\\Node\\Stmt\\PropertyProperty',
    30 => 'PhpParser\\Node\\Stmt\\Return_',
    31 => 'PhpParser\\Node\\Stmt\\Static_',
    32 => 'PhpParser\\Node\\Stmt\\StaticVar',
    33 => 'PhpParser\\Node\\Stmt\\Switch_',
    34 => 'PhpParser\\Node\\Stmt\\Throw_',
    35 => 'PhpParser\\Node\\Stmt\\Trait_',
    36 => 'PhpParser\\Node\\Stmt\\TraitUse',
    37 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation',
    38 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation\\Alias',
    39 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation\\Precedence',
    40 => 'PhpParser\\Node\\Stmt\\TryCatch',
    41 => 'PhpParser\\Node\\Stmt\\Unset_',
    42 => 'PhpParser\\Node\\Stmt\\Use_',
    43 => 'PhpParser\\Node\\Stmt\\UseUse',
    44 => 'PhpParser\\Node\\Stmt\\While_',
  ),
  'PhpParser\\Node\\Stmt\\ClassLike' => 
  array (
    0 => 'PhpParser\\Node\\Stmt\\Class_',
    1 => 'PhpParser\\Node\\Stmt\\Interface_',
    2 => 'PhpParser\\Node\\Stmt\\Trait_',
  ),
  'PhpParser\\Node\\Stmt\\TraitUseAdaptation' => 
  array (
    0 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation\\Alias',
    1 => 'PhpParser\\Node\\Stmt\\TraitUseAdaptation\\Precedence',
  ),
  'PhpParser\\NodeTraverserInterface' => 
  array (
    0 => 'PhpParser\\NodeTraverser',
  ),
  'PhpParser\\NodeVisitor' => 
  array (
    0 => 'PhpParser\\NodeVisitorAbstract',
    1 => 'PhpParser\\NodeVisitor\\NameResolver',
  ),
  'PhpParser\\NodeVisitorAbstract' => 
  array (
    0 => 'PhpParser\\NodeVisitor\\NameResolver',
  ),
  'PhpParser\\Parser' => 
  array (
    0 => 'PhpParser\\Parser\\Multiple',
    1 => 'PhpParser\\ParserAbstract',
    2 => 'PhpParser\\Parser\\Php5',
    3 => 'PhpParser\\Parser\\Php7',
  ),
  'PhpParser\\ParserAbstract' => 
  array (
    0 => 'PhpParser\\Parser\\Php5',
    1 => 'PhpParser\\Parser\\Php7',
  ),
  'PhpParser\\PrettyPrinterAbstract' => 
  array (
    0 => 'PhpParser\\PrettyPrinter\\Standard',
    1 => 'Famelo\\Beard\\Scaffold\\Builder\\Php\\Printer\\TYPO3Printer',
  ),
  'PhpParser\\Serializer' => 
  array (
    0 => 'PhpParser\\Serializer\\XML',
  ),
  'PhpParser\\Unserializer' => 
  array (
    0 => 'PhpParser\\Unserializer\\XML',
  ),
  'League\\Flysystem\\AdapterInterface' => 
  array (
    0 => 'League\\Flysystem\\Adapter\\AbstractAdapter',
    1 => 'League\\Flysystem\\Adapter\\AbstractFtpAdapter',
    2 => 'League\\Flysystem\\Sftp\\SftpAdapter',
    3 => 'League\\Flysystem\\Adapter\\Ftp',
    4 => 'League\\Flysystem\\Adapter\\Ftpd',
    5 => 'League\\Flysystem\\Adapter\\Local',
    6 => 'League\\Flysystem\\Adapter\\NullAdapter',
    7 => 'League\\Flysystem\\Adapter\\SynologyFtp',
  ),
  'League\\Flysystem\\ReadInterface' => 
  array (
    0 => 'League\\Flysystem\\Adapter\\AbstractAdapter',
    1 => 'League\\Flysystem\\Adapter\\AbstractFtpAdapter',
    2 => 'League\\Flysystem\\Sftp\\SftpAdapter',
    3 => 'League\\Flysystem\\Adapter\\Ftp',
    4 => 'League\\Flysystem\\Adapter\\Ftpd',
    5 => 'League\\Flysystem\\Adapter\\Local',
    6 => 'League\\Flysystem\\Adapter\\NullAdapter',
    7 => 'League\\Flysystem\\Adapter\\SynologyFtp',
  ),
  'League\\Flysystem\\Adapter\\AbstractAdapter' => 
  array (
    0 => 'League\\Flysystem\\Adapter\\AbstractFtpAdapter',
    1 => 'League\\Flysystem\\Sftp\\SftpAdapter',
    2 => 'League\\Flysystem\\Adapter\\Ftp',
    3 => 'League\\Flysystem\\Adapter\\Ftpd',
    4 => 'League\\Flysystem\\Adapter\\Local',
    5 => 'League\\Flysystem\\Adapter\\NullAdapter',
    6 => 'League\\Flysystem\\Adapter\\SynologyFtp',
  ),
  'League\\Flysystem\\Adapter\\AbstractFtpAdapter' => 
  array (
    0 => 'League\\Flysystem\\Sftp\\SftpAdapter',
    1 => 'League\\Flysystem\\Adapter\\Ftp',
    2 => 'League\\Flysystem\\Adapter\\Ftpd',
    3 => 'League\\Flysystem\\Adapter\\SynologyFtp',
  ),
  'League\\Flysystem\\Adapter\\Ftp' => 
  array (
    0 => 'League\\Flysystem\\Adapter\\Ftpd',
    1 => 'League\\Flysystem\\Adapter\\SynologyFtp',
  ),
  'League\\Flysystem\\Adapter\\Ftpd' => 
  array (
    0 => 'League\\Flysystem\\Adapter\\SynologyFtp',
  ),
  'League\\Flysystem\\Handler' => 
  array (
    0 => 'League\\Flysystem\\Directory',
    1 => 'League\\Flysystem\\File',
  ),
  'League\\Flysystem\\Exception' => 
  array (
    0 => 'League\\Flysystem\\FileExistsException',
    1 => 'League\\Flysystem\\FileNotFoundException',
    2 => 'League\\Flysystem\\UnreadableFileException',
  ),
  'League\\Flysystem\\FilesystemInterface' => 
  array (
    0 => 'League\\Flysystem\\Filesystem',
  ),
  'League\\Flysystem\\PluginInterface' => 
  array (
    0 => 'League\\Flysystem\\Plugin\\AbstractPlugin',
    1 => 'League\\Flysystem\\Plugin\\EmptyDir',
    2 => 'League\\Flysystem\\Plugin\\GetWithMetadata',
    3 => 'League\\Flysystem\\Plugin\\ListFiles',
    4 => 'League\\Flysystem\\Plugin\\ListPaths',
    5 => 'League\\Flysystem\\Plugin\\ListWith',
  ),
  'League\\Flysystem\\Plugin\\AbstractPlugin' => 
  array (
    0 => 'League\\Flysystem\\Plugin\\EmptyDir',
    1 => 'League\\Flysystem\\Plugin\\GetWithMetadata',
    2 => 'League\\Flysystem\\Plugin\\ListFiles',
    3 => 'League\\Flysystem\\Plugin\\ListPaths',
    4 => 'League\\Flysystem\\Plugin\\ListWith',
  ),
  'JsonSchema\\Exception\\InvalidArgumentException' => 
  array (
    0 => 'JsonSchema\\Exception\\InvalidSourceUriException',
  ),
  'JsonSchema\\Uri\\Retrievers\\UriRetrieverInterface' => 
  array (
    0 => 'JsonSchema\\Uri\\Retrievers\\AbstractRetriever',
    1 => 'JsonSchema\\Uri\\Retrievers\\Curl',
    2 => 'JsonSchema\\Uri\\Retrievers\\FileGetContents',
    3 => 'JsonSchema\\Uri\\Retrievers\\PredefinedArray',
  ),
  'JsonSchema\\Uri\\Retrievers\\AbstractRetriever' => 
  array (
    0 => 'JsonSchema\\Uri\\Retrievers\\Curl',
    1 => 'JsonSchema\\Uri\\Retrievers\\FileGetContents',
    2 => 'JsonSchema\\Uri\\Retrievers\\PredefinedArray',
  ),
  'FastRoute\\DataGenerator' => 
  array (
    0 => 'FastRoute\\DataGenerator\\RegexBasedAbstract',
    1 => 'FastRoute\\DataGenerator\\CharCountBased',
    2 => 'FastRoute\\DataGenerator\\GroupCountBased',
    3 => 'FastRoute\\DataGenerator\\GroupPosBased',
    4 => 'FastRoute\\DataGenerator\\MarkBased',
  ),
  'FastRoute\\DataGenerator\\RegexBasedAbstract' => 
  array (
    0 => 'FastRoute\\DataGenerator\\CharCountBased',
    1 => 'FastRoute\\DataGenerator\\GroupCountBased',
    2 => 'FastRoute\\DataGenerator\\GroupPosBased',
    3 => 'FastRoute\\DataGenerator\\MarkBased',
  ),
  'FastRoute\\Dispatcher' => 
  array (
    0 => 'FastRoute\\Dispatcher\\RegexBasedAbstract',
    1 => 'FastRoute\\Dispatcher\\CharCountBased',
    2 => 'FastRoute\\Dispatcher\\GroupCountBased',
    3 => 'FastRoute\\Dispatcher\\GroupPosBased',
    4 => 'FastRoute\\Dispatcher\\MarkBased',
  ),
  'FastRoute\\Dispatcher\\RegexBasedAbstract' => 
  array (
    0 => 'FastRoute\\Dispatcher\\CharCountBased',
    1 => 'FastRoute\\Dispatcher\\GroupCountBased',
    2 => 'FastRoute\\Dispatcher\\GroupPosBased',
    3 => 'FastRoute\\Dispatcher\\MarkBased',
  ),
  'FastRoute\\RouteParser' => 
  array (
    0 => 'FastRoute\\RouteParser\\Std',
  ),
  'Famelo\\Beard\\Scaffold\\Builder\\Php\\AbstractClassBuilder' => 
  array (
    0 => 'Famelo\\Beard\\Scaffold\\Builder\\Php\\ClassBuilder',
    1 => 'Famelo\\Beard\\Scaffold\\Builder\\Typo3\\ControllerBuilder',
    2 => 'Famelo\\Beard\\Scaffold\\Builder\\Typo3\\ModelBuilder',
  ),
  'PhpParser\\PrettyPrinter\\Standard' => 
  array (
    0 => 'Famelo\\Beard\\Scaffold\\Builder\\Php\\Printer\\TYPO3Printer',
  ),
  'Famelo\\Beard\\Scaffold\\Builder\\Php\\ClassBuilder' => 
  array (
    0 => 'Famelo\\Beard\\Scaffold\\Builder\\Typo3\\ControllerBuilder',
    1 => 'Famelo\\Beard\\Scaffold\\Builder\\Typo3\\ModelBuilder',
  ),
  'Famelo\\Beard\\Scaffold\\Core\\Packages\\PackageInterface' => 
  array (
    0 => 'Famelo\\Beard\\Scaffold\\Core\\Packages\\AbstractPackage',
    1 => 'Famelo\\Beard\\Scaffold\\Typo3\\ExtensionPackage',
  ),
  'Famelo\\Beard\\Scaffold\\Core\\Components\\AbstractComponent' => 
  array (
    0 => 'Famelo\\Beard\\Scaffold\\Typo3\\Components\\ControllerComponent',
    1 => 'Famelo\\Beard\\Scaffold\\Typo3\\Components\\FluidTypo3Component',
    2 => 'Famelo\\Beard\\Scaffold\\Typo3\\Components\\MetadataComponent',
    3 => 'Famelo\\Beard\\Scaffold\\Typo3\\Components\\ModelComponent',
    4 => 'Famelo\\Beard\\Scaffold\\Typo3\\Components\\PluginComponent',
  ),
  'Famelo\\Beard\\Scaffold\\Core\\Packages\\AbstractPackage' => 
  array (
    0 => 'Famelo\\Beard\\Scaffold\\Typo3\\ExtensionPackage',
  ),
  'Famelo\\Beard\\Scaffold\\Core\\Vendor\\VendorInterface' => 
  array (
    0 => 'Famelo\\Beard\\Scaffold\\TYPO3\\Typo3Vendor',
  ),
  'Famelo\\Beard\\Interfaces\\SystemSettingsInterface' => 
  array (
    0 => 'Famelo\\Beard\\Systems\\FlowSystem',
    1 => 'Famelo\\Beard\\Systems\\SymfonySystem',
    2 => 'Famelo\\Beard\\Systems\\Typo3System',
    3 => 'Famelo\\Beard\\Systems\\WordpressSettings',
  ),
  'Famelo\\Beard\\Interfaces\\Cache\\ClearInterface' => 
  array (
    0 => 'Famelo\\Beard\\Systems\\FlowSystem',
    1 => 'Famelo\\Beard\\Systems\\SymfonySystem',
    2 => 'Famelo\\Beard\\Systems\\Typo3System',
  ),
  'Famelo\\Beard\\Interfaces\\Cache\\WarmupInterface' => 
  array (
    0 => 'Famelo\\Beard\\Systems\\FlowSystem',
    1 => 'Famelo\\Beard\\Systems\\SymfonySystem',
  ),
  'Dotenv\\Exception\\ExceptionInterface' => 
  array (
    0 => 'Dotenv\\Exception\\InvalidCallbackException',
    1 => 'Dotenv\\Exception\\InvalidFileException',
    2 => 'Dotenv\\Exception\\InvalidPathException',
    3 => 'Dotenv\\Exception\\ValidationException',
  ),
  'Doctrine\\Instantiator\\Exception\\ExceptionInterface' => 
  array (
    0 => 'Doctrine\\Instantiator\\Exception\\InvalidArgumentException',
    1 => 'Doctrine\\Instantiator\\Exception\\UnexpectedValueException',
  ),
  'Doctrine\\Instantiator\\InstantiatorInterface' => 
  array (
    0 => 'Doctrine\\Instantiator\\Instantiator',
  ),
  'DeepCopy\\Filter\\Filter' => 
  array (
    0 => 'DeepCopy\\Filter\\Doctrine\\DoctrineCollectionFilter',
    1 => 'DeepCopy\\Filter\\Doctrine\\DoctrineEmptyCollectionFilter',
    2 => 'DeepCopy\\Filter\\KeepFilter',
    3 => 'DeepCopy\\Filter\\ReplaceFilter',
    4 => 'DeepCopy\\Filter\\SetNullFilter',
  ),
  'DeepCopy\\Matcher\\Matcher' => 
  array (
    0 => 'DeepCopy\\Matcher\\PropertyMatcher',
    1 => 'DeepCopy\\Matcher\\PropertyNameMatcher',
    2 => 'DeepCopy\\Matcher\\PropertyTypeMatcher',
  ),
  'DeepCopy\\TypeFilter\\TypeFilter' => 
  array (
    0 => 'DeepCopy\\TypeFilter\\ReplaceFilter',
    1 => 'DeepCopy\\TypeFilter\\ShallowCopyFilter',
  ),
);